#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.Address")
open class Address: JavaObject {
  /// Java method `equalsNonHost$okhttp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Address.equalsNonHost$okhttp(okhttp3.Address)
  /// ```
@JavaMethod
  open func equalsNonHost$okhttp(_ arg0: Address?) -> Bool

  /// Java method `-deprecated_proxyAuthenticator`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Authenticator okhttp3.Address.-deprecated_proxyAuthenticator()
  /// ```
@JavaMethod("-deprecated_proxyAuthenticator")
  open func `-deprecated_proxyAuthenticator`() -> Authenticator!

  /// Java method `-deprecated_connectionSpecs`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.List<okhttp3.ConnectionSpec> okhttp3.Address.-deprecated_connectionSpecs()
  /// ```
@JavaMethod("-deprecated_connectionSpecs")
  open func `-deprecated_connectionSpecs`() -> List<ConnectionSpec>!

  /// Java method `-deprecated_certificatePinner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.CertificatePinner okhttp3.Address.-deprecated_certificatePinner()
  /// ```
@JavaMethod("-deprecated_certificatePinner")
  open func `-deprecated_certificatePinner`() -> CertificatePinner!

  /// Java method `dns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Dns okhttp3.Address.dns()
  /// ```
@JavaMethod
  open func dns() -> Dns!

  /// Java method `proxyAuthenticator`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Authenticator okhttp3.Address.proxyAuthenticator()
  /// ```
@JavaMethod
  open func proxyAuthenticator() -> Authenticator!

  /// Java method `connectionSpecs`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.List<okhttp3.ConnectionSpec> okhttp3.Address.connectionSpecs()
  /// ```
@JavaMethod
  open func connectionSpecs() -> List<ConnectionSpec>!

  /// Java method `certificatePinner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.CertificatePinner okhttp3.Address.certificatePinner()
  /// ```
@JavaMethod
  open func certificatePinner() -> CertificatePinner!

  /// Java method `-deprecated_dns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Dns okhttp3.Address.-deprecated_dns()
  /// ```
@JavaMethod("-deprecated_dns")
  open func `-deprecated_dns`() -> Dns!

  /// Java method `-deprecated_url`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.HttpUrl okhttp3.Address.-deprecated_url()
  /// ```
@JavaMethod("-deprecated_url")
  open func `-deprecated_url`() -> HttpUrl!

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean okhttp3.Address.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String okhttp3.Address.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int okhttp3.Address.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `url`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.HttpUrl okhttp3.Address.url()
  /// ```
@JavaMethod
  open func url() -> HttpUrl!
}
#endif
