#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension CacheControl {
  @JavaClass("okhttp3.CacheControl$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getMaxAgeSeconds$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.CacheControl$Builder.getMaxAgeSeconds$okhttp()
    /// ```
  @JavaMethod
  open func getMaxAgeSeconds$okhttp() -> Int32

    /// Java method `setMaxAgeSeconds$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setMaxAgeSeconds$okhttp(int)
    /// ```
  @JavaMethod
  open func setMaxAgeSeconds$okhttp(_ arg0: Int32)

    /// Java method `getMaxStaleSeconds$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.CacheControl$Builder.getMaxStaleSeconds$okhttp()
    /// ```
  @JavaMethod
  open func getMaxStaleSeconds$okhttp() -> Int32

    /// Java method `setMaxStaleSeconds$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setMaxStaleSeconds$okhttp(int)
    /// ```
  @JavaMethod
  open func setMaxStaleSeconds$okhttp(_ arg0: Int32)

    /// Java method `getMinFreshSeconds$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.CacheControl$Builder.getMinFreshSeconds$okhttp()
    /// ```
  @JavaMethod
  open func getMinFreshSeconds$okhttp() -> Int32

    /// Java method `setMinFreshSeconds$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setMinFreshSeconds$okhttp(int)
    /// ```
  @JavaMethod
  open func setMinFreshSeconds$okhttp(_ arg0: Int32)

    /// Java method `getOnlyIfCached$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.CacheControl$Builder.getOnlyIfCached$okhttp()
    /// ```
  @JavaMethod
  open func getOnlyIfCached$okhttp() -> Bool

    /// Java method `setOnlyIfCached$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setOnlyIfCached$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setOnlyIfCached$okhttp(_ arg0: Bool)

    /// Java method `getNoTransform$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.CacheControl$Builder.getNoTransform$okhttp()
    /// ```
  @JavaMethod
  open func getNoTransform$okhttp() -> Bool

    /// Java method `setNoTransform$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setNoTransform$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setNoTransform$okhttp(_ arg0: Bool)

    /// Java method `getImmutable$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.CacheControl$Builder.getImmutable$okhttp()
    /// ```
  @JavaMethod
  open func getImmutable$okhttp() -> Bool

    /// Java method `setImmutable$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setImmutable$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setImmutable$okhttp(_ arg0: Bool)

    /// Java method `getNoCache$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.CacheControl$Builder.getNoCache$okhttp()
    /// ```
  @JavaMethod
  open func getNoCache$okhttp() -> Bool

    /// Java method `noCache`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.noCache()
    /// ```
  @JavaMethod
  open func noCache() -> CacheControl.Builder!

    /// Java method `setNoCache$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setNoCache$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setNoCache$okhttp(_ arg0: Bool)

    /// Java method `getNoStore$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.CacheControl$Builder.getNoStore$okhttp()
    /// ```
  @JavaMethod
  open func getNoStore$okhttp() -> Bool

    /// Java method `noStore`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.noStore()
    /// ```
  @JavaMethod
  open func noStore() -> CacheControl.Builder!

    /// Java method `setNoStore$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.CacheControl$Builder.setNoStore$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setNoStore$okhttp(_ arg0: Bool)

    /// Java method `onlyIfCached`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.onlyIfCached()
    /// ```
  @JavaMethod
  open func onlyIfCached() -> CacheControl.Builder!

    /// Java method `noTransform`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.noTransform()
    /// ```
  @JavaMethod
  open func noTransform() -> CacheControl.Builder!

    /// Java method `immutable`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.immutable()
    /// ```
  @JavaMethod
  open func immutable() -> CacheControl.Builder!

    /// Java method `maxAge-LRDsOJo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.maxAge-LRDsOJo(long)
    /// ```
  @JavaMethod("maxAge-LRDsOJo")
  open func `maxAge-LRDsOJo`(_ arg0: Int64) -> CacheControl.Builder!

    /// Java method `maxStale-LRDsOJo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.maxStale-LRDsOJo(long)
    /// ```
  @JavaMethod("maxStale-LRDsOJo")
  open func `maxStale-LRDsOJo`(_ arg0: Int64) -> CacheControl.Builder!

    /// Java method `minFresh-LRDsOJo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.minFresh-LRDsOJo(long)
    /// ```
  @JavaMethod("minFresh-LRDsOJo")
  open func `minFresh-LRDsOJo`(_ arg0: Int64) -> CacheControl.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl okhttp3.CacheControl$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> CacheControl!
  }
}
#endif
