// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension CertificatePinner {
  @JavaClass("okhttp3.CertificatePinner$Companion")
  open class Companion: JavaObject {

  }
}
#endif
