// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.CipherSuite")
open class CipherSuite: JavaObject {
  /// Java method `-deprecated_javaName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.CipherSuite.-deprecated_javaName()
  /// ```
@JavaMethod("-deprecated_javaName")
  open func `-deprecated_javaName`() -> String

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String okhttp3.CipherSuite.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `javaName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.CipherSuite.javaName()
  /// ```
@JavaMethod
  open func javaName() -> String
}
extension JavaClass<CipherSuite> {
  @JavaStaticField(isFinal: true)
  public var Companion: CipherSuite.Companion!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_NULL_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_NULL_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_EXPORT_WITH_RC4_40_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_RC4_128_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_EXPORT_WITH_DES40_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_DES_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_DES_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_DES_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_EXPORT_WITH_RC4_40_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_RC4_128_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_DES_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_WITH_DES_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_WITH_DES_CBC_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_WITH_3DES_EDE_CBC_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_WITH_RC4_128_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_EXPORT_WITH_RC4_40_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_KRB5_EXPORT_WITH_RC4_40_MD5: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_NULL_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_AES_256_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_CAMELLIA_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_AES_256_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_AES_256_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_AES_256_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_CAMELLIA_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_PSK_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_PSK_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_PSK_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_PSK_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_SEED_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_RSA_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_DSS_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DH_anon_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_EMPTY_RENEGOTIATION_INFO_SCSV: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_FALLBACK_SCSV: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_NULL_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_NULL_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_NULL_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_NULL_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_anon_WITH_NULL_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_anon_WITH_RC4_128_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_anon_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_anon_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_AES_128_GCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_AES_256_GCM_SHA384: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_CHACHA20_POLY1305_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_AES_128_CCM_SHA256: CipherSuite!

  @JavaStaticField(isFinal: true)
  public var TLS_AES_128_CCM_8_SHA256: CipherSuite!

    /// Java method `forJavaName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final synchronized okhttp3.CipherSuite okhttp3.CipherSuite.forJavaName(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func forJavaName(_ arg0: String) -> CipherSuite!
}
#endif
