// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension CipherSuite {
  @JavaClass("okhttp3.CipherSuite$Companion")
  open class Companion: JavaObject {
    /// Java method `forJavaName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized okhttp3.CipherSuite okhttp3.CipherSuite$Companion.forJavaName(java.lang.String)
    /// ```
  @JavaMethod
  open func forJavaName(_ arg0: String) -> CipherSuite!
  }
}
extension JavaClass<CipherSuite.Companion> {
  /// Java method `access$init`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static final okhttp3.CipherSuite okhttp3.CipherSuite$Companion.access$init(okhttp3.CipherSuite$Companion,java.lang.String,int)
  /// ```
@JavaStaticMethod
  public func access$init(_ arg0: CipherSuite.Companion?, _ arg1: String, _ arg2: Int32) -> CipherSuite!
}
#endif
