#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension CookieJar {
  @JavaClass("okhttp3.CookieJar$Companion")
  open class Companion: JavaObject {

  }
}
#endif
