// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Cookie {
  @JavaClass("okhttp3.Cookie$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Cookie?, environment: JNIEnvironment? = nil)

    /// Java method `expiresAt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.expiresAt(long)
    /// ```
  @JavaMethod
  open func expiresAt(_ arg0: Int64) -> Cookie.Builder!

    /// Java method `domain`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.domain(java.lang.String)
    /// ```
  @JavaMethod
  open func domain(_ arg0: String) -> Cookie.Builder!

    /// Java method `secure`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.secure()
    /// ```
  @JavaMethod
  open func secure() -> Cookie.Builder!

    /// Java method `httpOnly`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.httpOnly()
    /// ```
  @JavaMethod
  open func httpOnly() -> Cookie.Builder!

    /// Java method `sameSite`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.sameSite(java.lang.String)
    /// ```
  @JavaMethod
  open func sameSite(_ arg0: String) -> Cookie.Builder!

    /// Java method `hostOnlyDomain`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.hostOnlyDomain(java.lang.String)
    /// ```
  @JavaMethod
  open func hostOnlyDomain(_ arg0: String) -> Cookie.Builder!

    /// Java method `name`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.name(java.lang.String)
    /// ```
  @JavaMethod
  open func name(_ arg0: String) -> Cookie.Builder!

    /// Java method `value`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.value(java.lang.String)
    /// ```
  @JavaMethod
  open func value(_ arg0: String) -> Cookie.Builder!

    /// Java method `path`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie$Builder okhttp3.Cookie$Builder.path(java.lang.String)
    /// ```
  @JavaMethod
  open func path(_ arg0: String) -> Cookie.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie okhttp3.Cookie$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> Cookie!
  }
}
#endif
