#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Dns {
  @JavaClass("okhttp3.Dns$Companion")
  open class Companion: JavaObject {

  }
}
#endif
