// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("okhttp3.Dns")
public struct Dns {

}
extension JavaClass<Dns> {
  @JavaStaticField(isFinal: true)
  public var Companion: Dns.Companion!

  @JavaStaticField(isFinal: true)
  public var SYSTEM: Dns!
}
#endif
