#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Headers {
  @JavaClass("okhttp3.Headers$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getNamesAndValues$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.Headers$Builder.getNamesAndValues$okhttp()
    /// ```
  @JavaMethod
  open func getNamesAndValues$okhttp() -> List<JavaString>!

    /// Java method `addUnsafeNonAscii`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.addUnsafeNonAscii(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addUnsafeNonAscii(_ arg0: String, _ arg1: String) -> Headers.Builder!

    /// Java method `addLenient$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.addLenient$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func addLenient$okhttp(_ arg0: String) -> Headers.Builder!

    /// Java method `addLenient$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.addLenient$okhttp(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addLenient$okhttp(_ arg0: String, _ arg1: String) -> Headers.Builder!

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Headers$Builder.get(java.lang.String)
    /// ```
  @JavaMethod
  open func get(_ arg0: String) -> String

    /// Java method `add`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.add(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func add(_ arg0: String, _ arg1: String) -> Headers.Builder!

    /// Java method `add`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.add(java.lang.String)
    /// ```
  @JavaMethod
  open func add(_ arg0: String) -> Headers.Builder!

    /// Java method `addAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.addAll(okhttp3.Headers)
    /// ```
  @JavaMethod
  open func addAll(_ arg0: Headers?) -> Headers.Builder!

    /// Java method `set`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.set(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func set(_ arg0: String, _ arg1: String) -> Headers.Builder!

    /// Java method `removeAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Headers$Builder.removeAll(java.lang.String)
    /// ```
  @JavaMethod
  open func removeAll(_ arg0: String) -> Headers.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers okhttp3.Headers$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> Headers!
  }
}
#endif
