#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Headers {
  @JavaClass("okhttp3.Headers$Companion")
  open class Companion: JavaObject {
    /// Java method `-deprecated_of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers okhttp3.Headers$Companion.-deprecated_of(java.lang.String...)
    /// ```
  @JavaMethod("-deprecated_of")
  open func `-deprecated_of`(_ arg0: [String]) -> Headers!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers okhttp3.Headers$Companion.of(java.lang.String...)
    /// ```
  @JavaMethod
  open func of(_ arg0: [String]) -> Headers!
  }
}
#endif
