// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension HttpUrl {
  @JavaClass("okhttp3.HttpUrl$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `reencodeForUri$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.reencodeForUri$okhttp()
    /// ```
  @JavaMethod
  open func reencodeForUri$okhttp() -> HttpUrl.Builder!

    /// Java method `setEncodedUsername$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.HttpUrl$Builder.setEncodedUsername$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func setEncodedUsername$okhttp(_ arg0: String)

    /// Java method `setEncodedPassword$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.HttpUrl$Builder.setEncodedPassword$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func setEncodedPassword$okhttp(_ arg0: String)

    /// Java method `getEncodedPathSegments$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl$Builder.getEncodedPathSegments$okhttp()
    /// ```
  @JavaMethod
  open func getEncodedPathSegments$okhttp() -> List<JavaString>!

    /// Java method `setEncodedFragment$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.HttpUrl$Builder.setEncodedFragment$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func setEncodedFragment$okhttp(_ arg0: String)

    /// Java method `getEncodedUsername$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl$Builder.getEncodedUsername$okhttp()
    /// ```
  @JavaMethod
  open func getEncodedUsername$okhttp() -> String

    /// Java method `getEncodedPassword$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl$Builder.getEncodedPassword$okhttp()
    /// ```
  @JavaMethod
  open func getEncodedPassword$okhttp() -> String

    /// Java method `getEncodedFragment$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl$Builder.getEncodedFragment$okhttp()
    /// ```
  @JavaMethod
  open func getEncodedFragment$okhttp() -> String

    /// Java method `addEncodedPathSegment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.addEncodedPathSegment(java.lang.String)
    /// ```
  @JavaMethod
  open func addEncodedPathSegment(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `addEncodedPathSegments`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.addEncodedPathSegments(java.lang.String)
    /// ```
  @JavaMethod
  open func addEncodedPathSegments(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `setEncodedPathSegment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.setEncodedPathSegment(int,java.lang.String)
    /// ```
  @JavaMethod
  open func setEncodedPathSegment(_ arg0: Int32, _ arg1: String) -> HttpUrl.Builder!

    /// Java method `addEncodedQueryParameter`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.addEncodedQueryParameter(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addEncodedQueryParameter(_ arg0: String, _ arg1: String) -> HttpUrl.Builder!

    /// Java method `removeAllQueryParameters`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.removeAllQueryParameters(java.lang.String)
    /// ```
  @JavaMethod
  open func removeAllQueryParameters(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `setEncodedQueryParameter`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.setEncodedQueryParameter(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func setEncodedQueryParameter(_ arg0: String, _ arg1: String) -> HttpUrl.Builder!

    /// Java method `removeAllEncodedQueryParameters`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.removeAllEncodedQueryParameters(java.lang.String)
    /// ```
  @JavaMethod
  open func removeAllEncodedQueryParameters(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `parse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.parse$okhttp(okhttp3.HttpUrl,java.lang.String)
    /// ```
  @JavaMethod
  open func parse$okhttp(_ arg0: HttpUrl?, _ arg1: String) -> HttpUrl.Builder!

    /// Java method `username`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.username(java.lang.String)
    /// ```
  @JavaMethod
  open func username(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `password`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.password(java.lang.String)
    /// ```
  @JavaMethod
  open func password(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `encodedUsername`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.encodedUsername(java.lang.String)
    /// ```
  @JavaMethod
  open func encodedUsername(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `encodedPassword`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.encodedPassword(java.lang.String)
    /// ```
  @JavaMethod
  open func encodedPassword(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `encodedPath`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.encodedPath(java.lang.String)
    /// ```
  @JavaMethod
  open func encodedPath(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `encodedQuery`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.encodedQuery(java.lang.String)
    /// ```
  @JavaMethod
  open func encodedQuery(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `encodedFragment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.encodedFragment(java.lang.String)
    /// ```
  @JavaMethod
  open func encodedFragment(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `setScheme$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.HttpUrl$Builder.setScheme$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func setScheme$okhttp(_ arg0: String)

    /// Java method `setHost$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.HttpUrl$Builder.setHost$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func setHost$okhttp(_ arg0: String)

    /// Java method `setPort$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.HttpUrl$Builder.setPort$okhttp(int)
    /// ```
  @JavaMethod
  open func setPort$okhttp(_ arg0: Int32)

    /// Java method `getScheme$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl$Builder.getScheme$okhttp()
    /// ```
  @JavaMethod
  open func getScheme$okhttp() -> String

    /// Java method `getHost$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl$Builder.getHost$okhttp()
    /// ```
  @JavaMethod
  open func getHost$okhttp() -> String

    /// Java method `getPort$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl$Builder.getPort$okhttp()
    /// ```
  @JavaMethod
  open func getPort$okhttp() -> Int32

    /// Java method `addPathSegment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.addPathSegment(java.lang.String)
    /// ```
  @JavaMethod
  open func addPathSegment(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `addPathSegments`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.addPathSegments(java.lang.String)
    /// ```
  @JavaMethod
  open func addPathSegments(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `setPathSegment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.setPathSegment(int,java.lang.String)
    /// ```
  @JavaMethod
  open func setPathSegment(_ arg0: Int32, _ arg1: String) -> HttpUrl.Builder!

    /// Java method `removePathSegment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.removePathSegment(int)
    /// ```
  @JavaMethod
  open func removePathSegment(_ arg0: Int32) -> HttpUrl.Builder!

    /// Java method `addQueryParameter`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.addQueryParameter(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addQueryParameter(_ arg0: String, _ arg1: String) -> HttpUrl.Builder!

    /// Java method `setQueryParameter`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.setQueryParameter(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func setQueryParameter(_ arg0: String, _ arg1: String) -> HttpUrl.Builder!

    /// Java method `getEncodedQueryNamesAndValues$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl$Builder.getEncodedQueryNamesAndValues$okhttp()
    /// ```
  @JavaMethod
  open func getEncodedQueryNamesAndValues$okhttp() -> List<JavaString>!

    /// Java method `setEncodedQueryNamesAndValues$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.HttpUrl$Builder.setEncodedQueryNamesAndValues$okhttp(java.util.List<java.lang.String>)
    /// ```
  @JavaMethod
  open func setEncodedQueryNamesAndValues$okhttp(_ arg0: List<JavaString>?)

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String okhttp3.HttpUrl$Builder.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `port`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.port(int)
    /// ```
  @JavaMethod
  open func port(_ arg0: Int32) -> HttpUrl.Builder!

    /// Java method `host`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.host(java.lang.String)
    /// ```
  @JavaMethod
  open func host(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `query`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.query(java.lang.String)
    /// ```
  @JavaMethod
  open func query(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> HttpUrl!

    /// Java method `scheme`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.scheme(java.lang.String)
    /// ```
  @JavaMethod
  open func scheme(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `fragment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.fragment(java.lang.String)
    /// ```
  @JavaMethod
  open func fragment(_ arg0: String) -> HttpUrl.Builder!
  }
}
#endif
