#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension HttpUrl {
  @JavaClass("okhttp3.HttpUrl$Companion")
  open class Companion: JavaObject {
    /// Java method `defaultPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl$Companion.defaultPort(java.lang.String)
    /// ```
  @JavaMethod
  open func defaultPort(_ arg0: String) -> Int32

    /// Java method `-deprecated_get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.-deprecated_get(java.net.URL)
    /// ```
  @JavaMethod("-deprecated_get")
  open func `-deprecated_get`(_ arg0: JavaURL?) -> HttpUrl!

    /// Java method `-deprecated_get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.-deprecated_get(java.lang.String)
    /// ```
  @JavaMethod("-deprecated_get")
  open func `-deprecated_get`(_ arg0: String) -> HttpUrl!

    /// Java method `-deprecated_parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.-deprecated_parse(java.lang.String)
    /// ```
  @JavaMethod("-deprecated_parse")
  open func `-deprecated_parse`(_ arg0: String) -> HttpUrl!

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.get(java.lang.String)
    /// ```
  @JavaMethod
  open func get(_ arg0: String) -> HttpUrl!

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.get(java.net.URL)
    /// ```
  @JavaMethod
  open func get(_ arg0: JavaURL?) -> HttpUrl!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.parse(java.lang.String)
    /// ```
  @JavaMethod
  open func parse(_ arg0: String) -> HttpUrl!
  }
}
#endif
