// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension MediaType {
  @JavaClass("okhttp3.MediaType$Companion")
  open class Companion: JavaObject {
    /// Java method `-deprecated_get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MediaType okhttp3.MediaType$Companion.-deprecated_get(java.lang.String)
    /// ```
  @JavaMethod("-deprecated_get")
  open func `-deprecated_get`(_ arg0: String) -> MediaType!

    /// Java method `-deprecated_parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MediaType okhttp3.MediaType$Companion.-deprecated_parse(java.lang.String)
    /// ```
  @JavaMethod("-deprecated_parse")
  open func `-deprecated_parse`(_ arg0: String) -> MediaType!

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MediaType okhttp3.MediaType$Companion.get(java.lang.String)
    /// ```
  @JavaMethod
  open func get(_ arg0: String) -> MediaType!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MediaType okhttp3.MediaType$Companion.parse(java.lang.String)
    /// ```
  @JavaMethod
  open func parse(_ arg0: String) -> MediaType!
  }
}
#endif
