// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension MultipartReader {
  @JavaClass("okhttp3.MultipartReader$Companion")
  open class Companion: JavaObject {

  }
}
#endif
