// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension OkHttpClient {
  @JavaClass("okhttp3.OkHttpClient$Companion")
  open class Companion: JavaObject {
    /// Java method `getDEFAULT_CONNECTION_SPECS$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.ConnectionSpec> okhttp3.OkHttpClient$Companion.getDEFAULT_CONNECTION_SPECS$okhttp()
    /// ```
  @JavaMethod
  open func getDEFAULT_CONNECTION_SPECS$okhttp() -> List<ConnectionSpec>!
  }
}
#endif
