#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.RequestBody")
open class RequestBody: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `contentType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract okhttp3.MediaType okhttp3.RequestBody.contentType()
    /// ```
  @JavaMethod
  open func contentType() -> MediaType!

    /// Java method `contentLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long okhttp3.RequestBody.contentLength() throws java.io.IOException
    /// ```
  @JavaMethod
  open func contentLength() throws -> Int64

    /// Java method `isDuplex`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean okhttp3.RequestBody.isDuplex()
    /// ```
  @JavaMethod
  open func isDuplex() -> Bool

    /// Java method `isOneShot`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean okhttp3.RequestBody.isOneShot()
    /// ```
  @JavaMethod
  open func isOneShot() -> Bool
}
extension JavaClass<RequestBody> {
  @JavaStaticField(isFinal: true)
  public var Companion: RequestBody.Companion!

  @JavaStaticField(isFinal: true)
  public var EMPTY: RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(byte[],okhttp3.MediaType)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: [Int8], _ arg1: MediaType?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(byte[],okhttp3.MediaType,int)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: [Int8], _ arg1: MediaType?, _ arg2: Int32) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(okhttp3.MediaType,java.io.File)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: File?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(okhttp3.MediaType,byte[],int,int)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: [Int8], _ arg2: Int32, _ arg3: Int32) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(java.io.File,okhttp3.MediaType)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: File?, _ arg1: MediaType?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(okhttp3.MediaType,byte[])
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: [Int8]) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(okhttp3.MediaType,byte[],int)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: [Int8], _ arg2: Int32) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(byte[])
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: [Int8]) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(byte[],okhttp3.MediaType,int,int)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: [Int8], _ arg1: MediaType?, _ arg2: Int32, _ arg3: Int32) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String,okhttp3.MediaType)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: String, _ arg1: MediaType?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.RequestBody okhttp3.RequestBody.create(okhttp3.MediaType,java.lang.String)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: String) -> RequestBody!
}
#endif
