#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension RequestBody {
  @JavaClass("okhttp3.RequestBody$Companion")
  open class Companion: JavaObject {
    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(byte[],okhttp3.MediaType)
    /// ```
  @JavaMethod
  open func create(_ arg0: [Int8], _ arg1: MediaType?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(byte[],okhttp3.MediaType,int)
    /// ```
  @JavaMethod
  open func create(_ arg0: [Int8], _ arg1: MediaType?, _ arg2: Int32) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(okhttp3.MediaType,java.io.File)
    /// ```
  @JavaMethod
  open func create(_ arg0: MediaType?, _ arg1: File?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(java.lang.String,okhttp3.MediaType)
    /// ```
  @JavaMethod
  open func create(_ arg0: String, _ arg1: MediaType?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(okhttp3.MediaType,byte[])
    /// ```
  @JavaMethod
  open func create(_ arg0: MediaType?, _ arg1: [Int8]) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(okhttp3.MediaType,byte[],int)
    /// ```
  @JavaMethod
  open func create(_ arg0: MediaType?, _ arg1: [Int8], _ arg2: Int32) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(byte[])
    /// ```
  @JavaMethod
  open func create(_ arg0: [Int8]) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(byte[],okhttp3.MediaType,int,int)
    /// ```
  @JavaMethod
  open func create(_ arg0: [Int8], _ arg1: MediaType?, _ arg2: Int32, _ arg3: Int32) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(java.io.File,okhttp3.MediaType)
    /// ```
  @JavaMethod
  open func create(_ arg0: File?, _ arg1: MediaType?) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(okhttp3.MediaType,java.lang.String)
    /// ```
  @JavaMethod
  open func create(_ arg0: MediaType?, _ arg1: String) -> RequestBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.RequestBody$Companion.create(okhttp3.MediaType,byte[],int,int)
    /// ```
  @JavaMethod
  open func create(_ arg0: MediaType?, _ arg1: [Int8], _ arg2: Int32, _ arg3: Int32) -> RequestBody!
  }
}
extension JavaClass<RequestBody.Companion> {
  /// Java method `create$default`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static okhttp3.RequestBody okhttp3.RequestBody$Companion.create$default(okhttp3.RequestBody$Companion,java.io.File,okhttp3.MediaType,int,java.lang.Object)
  /// ```
@JavaStaticMethod
  public func create$default(_ arg0: RequestBody.Companion?, _ arg1: File?, _ arg2: MediaType?, _ arg3: Int32, _ arg4: JavaObject?) -> RequestBody!

  /// Java method `create$default`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static okhttp3.RequestBody okhttp3.RequestBody$Companion.create$default(okhttp3.RequestBody$Companion,byte[],okhttp3.MediaType,int,int,int,java.lang.Object)
  /// ```
@JavaStaticMethod
  public func create$default(_ arg0: RequestBody.Companion?, _ arg1: [Int8], _ arg2: MediaType?, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: JavaObject?) -> RequestBody!

  /// Java method `create$default`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static okhttp3.RequestBody okhttp3.RequestBody$Companion.create$default(okhttp3.RequestBody$Companion,java.lang.String,okhttp3.MediaType,int,java.lang.Object)
  /// ```
@JavaStaticMethod
  public func create$default(_ arg0: RequestBody.Companion?, _ arg1: String, _ arg2: MediaType?, _ arg3: Int32, _ arg4: JavaObject?) -> RequestBody!

  /// Java method `create$default`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static okhttp3.RequestBody okhttp3.RequestBody$Companion.create$default(okhttp3.RequestBody$Companion,okhttp3.MediaType,byte[],int,int,int,java.lang.Object)
  /// ```
@JavaStaticMethod
  public func create$default(_ arg0: RequestBody.Companion?, _ arg1: MediaType?, _ arg2: [Int8], _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: JavaObject?) -> RequestBody!
}
#endif
