// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Request {
  @JavaClass("okhttp3.Request$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Request?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getCacheUrlOverride$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.Request$Builder.getCacheUrlOverride$okhttp()
    /// ```
  @JavaMethod
  open func getCacheUrlOverride$okhttp() -> HttpUrl!

    /// Java method `setCacheUrlOverride$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Request$Builder.setCacheUrlOverride$okhttp(okhttp3.HttpUrl)
    /// ```
  @JavaMethod
  open func setCacheUrlOverride$okhttp(_ arg0: HttpUrl?)

    /// Java method `headers`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.headers(okhttp3.Headers)
    /// ```
  @JavaMethod
  open func headers(_ arg0: Headers?) -> Request.Builder!

    /// Java method `getUrl$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.Request$Builder.getUrl$okhttp()
    /// ```
  @JavaMethod
  open func getUrl$okhttp() -> HttpUrl!

    /// Java method `setUrl$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Request$Builder.setUrl$okhttp(okhttp3.HttpUrl)
    /// ```
  @JavaMethod
  open func setUrl$okhttp(_ arg0: HttpUrl?)

    /// Java method `getMethod$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Request$Builder.getMethod$okhttp()
    /// ```
  @JavaMethod
  open func getMethod$okhttp() -> String

    /// Java method `setMethod$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Request$Builder.setMethod$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func setMethod$okhttp(_ arg0: String)

    /// Java method `getHeaders$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Request$Builder.getHeaders$okhttp()
    /// ```
  @JavaMethod
  open func getHeaders$okhttp() -> Headers.Builder!

    /// Java method `setHeaders$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Request$Builder.setHeaders$okhttp(okhttp3.Headers$Builder)
    /// ```
  @JavaMethod
  open func setHeaders$okhttp(_ arg0: Headers.Builder?)

    /// Java method `getBody$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.Request$Builder.getBody$okhttp()
    /// ```
  @JavaMethod
  open func getBody$okhttp() -> RequestBody!

    /// Java method `setBody$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Request$Builder.setBody$okhttp(okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func setBody$okhttp(_ arg0: RequestBody?)

    /// Java method `cacheUrlOverride`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Request$Builder okhttp3.Request$Builder.cacheUrlOverride(okhttp3.HttpUrl)
    /// ```
  @JavaMethod
  open func cacheUrlOverride(_ arg0: HttpUrl?) -> Request.Builder!

    /// Java method `addHeader`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.addHeader(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addHeader(_ arg0: String, _ arg1: String) -> Request.Builder!

    /// Java method `removeHeader`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.removeHeader(java.lang.String)
    /// ```
  @JavaMethod
  open func removeHeader(_ arg0: String) -> Request.Builder!

    /// Java method `cacheControl`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.cacheControl(okhttp3.CacheControl)
    /// ```
  @JavaMethod
  open func cacheControl(_ arg0: CacheControl?) -> Request.Builder!

    /// Java method `reifiedTag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final <T> okhttp3.Request$Builder okhttp3.Request$Builder.reifiedTag(T)
    /// ```
  @JavaMethod
  open func reifiedTag<T: AnyJavaObject>(_ arg0: T?) -> Request.Builder!

    /// Java method `gzip`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Request$Builder okhttp3.Request$Builder.gzip()
    /// ```
  @JavaMethod
  open func gzip() -> Request.Builder!

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.get()
    /// ```
  @JavaMethod
  open func get() -> Request.Builder!

    /// Java method `put`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.put(okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func put(_ arg0: RequestBody?) -> Request.Builder!

    /// Java method `method`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.method(java.lang.String,okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func method(_ arg0: String, _ arg1: RequestBody?) -> Request.Builder!

    /// Java method `url`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.url(java.net.URL)
    /// ```
  @JavaMethod
  open func url(_ arg0: JavaURL?) -> Request.Builder!

    /// Java method `url`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.url(java.lang.String)
    /// ```
  @JavaMethod
  open func url(_ arg0: String) -> Request.Builder!

    /// Java method `url`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.url(okhttp3.HttpUrl)
    /// ```
  @JavaMethod
  open func url(_ arg0: HttpUrl?) -> Request.Builder!

    /// Java method `delete`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Request$Builder okhttp3.Request$Builder.delete()
    /// ```
  @JavaMethod
  open func delete() -> Request.Builder!

    /// Java method `delete`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.delete(okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func delete(_ arg0: RequestBody?) -> Request.Builder!

    /// Java method `query`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.query(okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func query(_ arg0: RequestBody?) -> Request.Builder!

    /// Java method `head`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.head()
    /// ```
  @JavaMethod
  open func head() -> Request.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request okhttp3.Request$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> Request!

    /// Java method `tag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public <T> okhttp3.Request$Builder okhttp3.Request$Builder.tag(java.lang.Class<? super T>,T)
    /// ```
  @JavaMethod
  open func tag<T: AnyJavaObject>(_ arg0: JavaClass<JavaObject>?, _ arg1: T?) -> Request.Builder!

    /// Java method `tag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.tag(java.lang.Object)
    /// ```
  @JavaMethod
  open func tag(_ arg0: JavaObject?) -> Request.Builder!

    /// Java method `patch`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.patch(okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func patch(_ arg0: RequestBody?) -> Request.Builder!

    /// Java method `post`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.post(okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func post(_ arg0: RequestBody?) -> Request.Builder!

    /// Java method `header`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Request$Builder okhttp3.Request$Builder.header(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func header(_ arg0: String, _ arg1: String) -> Request.Builder!
  }
}
extension JavaClass<Request.Builder> {
  /// Java method `delete$default`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static okhttp3.Request$Builder okhttp3.Request$Builder.delete$default(okhttp3.Request$Builder,okhttp3.RequestBody,int,java.lang.Object)
  /// ```
@JavaStaticMethod
  public func delete$default(_ arg0: Request.Builder?, _ arg1: RequestBody?, _ arg2: Int32, _ arg3: JavaObject?) -> Request.Builder!
}
#endif
