// swift-format-ignore-file
#if !OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.ResponseBody", implements: Closeable.self)
open class ResponseBody: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `contentType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract okhttp3.MediaType okhttp3.ResponseBody.contentType()
    /// ```
  @JavaMethod
  open func contentType() -> MediaType!

    /// Java method `contentLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract long okhttp3.ResponseBody.contentLength()
    /// ```
  @JavaMethod
  open func contentLength() -> Int64

    /// Java method `byteStream`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.io.InputStream okhttp3.ResponseBody.byteStream()
    /// ```
  @JavaMethod
  open func byteStream() -> InputStream!

    /// Java method `bytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final byte[] okhttp3.ResponseBody.bytes() throws java.io.IOException
    /// ```
  @JavaMethod
  open func bytes() throws -> [Int8]

    /// Java method `source`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract okio.BufferedSource okhttp3.ResponseBody.source()
    /// ```
  @JavaMethod
  open func source() -> BufferedSource!

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.ResponseBody.close()
    /// ```
  @JavaMethod
  open func close()

    /// Java method `string`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.ResponseBody.string() throws java.io.IOException
    /// ```
  @JavaMethod
  open func string() throws -> String
}
extension JavaClass<ResponseBody> {
  @JavaStaticField(isFinal: true)
  public var Companion: ResponseBody.Companion!

  @JavaStaticField(isFinal: true)
  public var EMPTY: ResponseBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.ResponseBody okhttp3.ResponseBody.create(okhttp3.MediaType,byte[])
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: [Int8]) -> ResponseBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.ResponseBody okhttp3.ResponseBody.create(okhttp3.MediaType,java.lang.String)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: String) -> ResponseBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.ResponseBody okhttp3.ResponseBody.create(okhttp3.MediaType,long,okio.BufferedSource)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: MediaType?, _ arg1: Int64, _ arg2: BufferedSource?) -> ResponseBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.ResponseBody okhttp3.ResponseBody.create(java.lang.String,okhttp3.MediaType)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: String, _ arg1: MediaType?) -> ResponseBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.ResponseBody okhttp3.ResponseBody.create(byte[],okhttp3.MediaType)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: [Int8], _ arg1: MediaType?) -> ResponseBody!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.ResponseBody okhttp3.ResponseBody.create(okio.BufferedSource,okhttp3.MediaType,long)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: BufferedSource?, _ arg1: MediaType?, _ arg2: Int64) -> ResponseBody!
}
#endif
