/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.concurrent.ExecutionException;

public class App {
    public static void main(String[] args) throws ExecutionException, InterruptedException {
        System.out.println("Running Java code, first loading lib...");
        System.loadLibrary("SampleLib");
        System.out.println("Lib loaded, calling Swift...");

        com.madsodgaard.samplelib.SampleLib.run().get();

        System.out.println("All done!");
    }
}
