#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Cache {
  @JavaClass("okhttp3.Cache$Companion")
  open class Companion: JavaObject {
    /// Java method `hasVaryAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.Cache$Companion.hasVaryAll(okhttp3.Response)
    /// ```
  @JavaMethod
  open func hasVaryAll(_ arg0: Response?) -> Bool

    /// Java method `readInt$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.Cache$Companion.readInt$okhttp(okio.BufferedSource) throws java.io.IOException
    /// ```
  @JavaMethod
  open func readInt$okhttp(_ arg0: BufferedSource?) throws -> Int32

    /// Java method `varyMatches`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.Cache$Companion.varyMatches(okhttp3.Response,okhttp3.Headers,okhttp3.Request)
    /// ```
  @JavaMethod
  open func varyMatches(_ arg0: Response?, _ arg1: Headers?, _ arg2: Request?) -> Bool

    /// Java method `varyHeaders`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers okhttp3.Cache$Companion.varyHeaders(okhttp3.Response)
    /// ```
  @JavaMethod
  open func varyHeaders(_ arg0: Response?) -> Headers!

    /// Java method `key`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Cache$Companion.key(okhttp3.HttpUrl)
    /// ```
  @JavaMethod
  open func key(_ arg0: HttpUrl?) -> String
  }
}
#endif
