// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.Cache", implements: Closeable.self, Flushable.self)
open class Cache: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: Int64, environment: JNIEnvironment? = nil)

    /// Java method `getWriteSuccessCount$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.Cache.getWriteSuccessCount$okhttp()
    /// ```
  @JavaMethod
  open func getWriteSuccessCount$okhttp() -> Int32

    /// Java method `setWriteSuccessCount$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Cache.setWriteSuccessCount$okhttp(int)
    /// ```
  @JavaMethod
  open func setWriteSuccessCount$okhttp(_ arg0: Int32)

    /// Java method `-deprecated_directory`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.io.File okhttp3.Cache.-deprecated_directory()
    /// ```
  @JavaMethod("-deprecated_directory")
  open func `-deprecated_directory`() -> File!

    /// Java method `trackConditionalCacheHit$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized void okhttp3.Cache.trackConditionalCacheHit$okhttp()
    /// ```
  @JavaMethod
  open func trackConditionalCacheHit$okhttp()

    /// Java method `evictAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Cache.evictAll() throws java.io.IOException
    /// ```
  @JavaMethod
  open func evictAll() throws

    /// Java method `getWriteAbortCount$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.Cache.getWriteAbortCount$okhttp()
    /// ```
  @JavaMethod
  open func getWriteAbortCount$okhttp() -> Int32

    /// Java method `setWriteAbortCount$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Cache.setWriteAbortCount$okhttp(int)
    /// ```
  @JavaMethod
  open func setWriteAbortCount$okhttp(_ arg0: Int32)

    /// Java method `writeSuccessCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Cache.writeSuccessCount()
    /// ```
  @JavaMethod
  open func writeSuccessCount() -> Int32

    /// Java method `writeAbortCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Cache.writeAbortCount()
    /// ```
  @JavaMethod
  open func writeAbortCount() -> Int32

    /// Java method `isClosed`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.Cache.isClosed()
    /// ```
  @JavaMethod
  open func isClosed() -> Bool

    /// Java method `get$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Response okhttp3.Cache.get$okhttp(okhttp3.Request)
    /// ```
  @JavaMethod
  open func get$okhttp(_ arg0: Request?) -> Response!

    /// Java method `remove$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Cache.remove$okhttp(okhttp3.Request) throws java.io.IOException
    /// ```
  @JavaMethod
  open func remove$okhttp(_ arg0: Request?) throws

    /// Java method `update$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Cache.update$okhttp(okhttp3.Response,okhttp3.Response)
    /// ```
  @JavaMethod
  open func update$okhttp(_ arg0: Response?, _ arg1: Response?)

    /// Java method `requestCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Cache.requestCount()
    /// ```
  @JavaMethod
  open func requestCount() -> Int32

    /// Java method `networkCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Cache.networkCount()
    /// ```
  @JavaMethod
  open func networkCount() -> Int32

    /// Java method `hitCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Cache.hitCount()
    /// ```
  @JavaMethod
  open func hitCount() -> Int32

    /// Java method `size`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final long okhttp3.Cache.size() throws java.io.IOException
    /// ```
  @JavaMethod
  open func size() throws -> Int64

    /// Java method `maxSize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final long okhttp3.Cache.maxSize()
    /// ```
  @JavaMethod
  open func maxSize() -> Int64

    /// Java method `flush`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.Cache.flush() throws java.io.IOException
    /// ```
  @JavaMethod
  open func flush() throws

    /// Java method `initialize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Cache.initialize() throws java.io.IOException
    /// ```
  @JavaMethod
  open func initialize() throws

    /// Java method `directory`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.io.File okhttp3.Cache.directory()
    /// ```
  @JavaMethod
  open func directory() -> File!

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.Cache.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open func close() throws

    /// Java method `delete`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Cache.delete() throws java.io.IOException
    /// ```
  @JavaMethod
  open func delete() throws

    /// Java method `urls`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.Iterator<java.lang.String> okhttp3.Cache.urls() throws java.io.IOException
    /// ```
  @JavaMethod
  open func urls() throws -> JavaIterator<JavaString>!
}
extension JavaClass<Cache> {
  @JavaStaticField(isFinal: true)
  public var Companion: Cache.Companion!

    /// Java method `key`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final java.lang.String okhttp3.Cache.key(okhttp3.HttpUrl)
    /// ```
  @JavaStaticMethod
  public func key(_ arg0: HttpUrl?) -> String
}
#endif
