#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("okhttp3.Call")
public struct Call {
  /// Java method `isExecuted`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean okhttp3.Call.isExecuted()
  /// ```
@JavaMethod
  public func isExecuted() -> Bool

  /// Java method `isCanceled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean okhttp3.Call.isCanceled()
  /// ```
@JavaMethod
  public func isCanceled() -> Bool

  /// Java method `clone`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract okhttp3.Call okhttp3.Call.clone()
  /// ```
@JavaMethod
  public func clone() -> Call!

  /// Java method `enqueue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void okhttp3.Call.enqueue(okhttp3.Callback)
  /// ```
@JavaMethod
  public func enqueue(_ arg0: Callback?)

  /// Java method `cancel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void okhttp3.Call.cancel()
  /// ```
@JavaMethod
  public func cancel()

  /// Java method `execute`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract okhttp3.Response okhttp3.Call.execute() throws java.io.IOException
  /// ```
@JavaMethod
  public func execute() throws -> Response!

  /// Java method `request`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract okhttp3.Request okhttp3.Call.request()
  /// ```
@JavaMethod
  public func request() -> Request!
}
#endif
