// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension CertificatePinner {
  @JavaClass("okhttp3.CertificatePinner$Pin")
  open class Pin: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

    /// Java method `getHashAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.CertificatePinner$Pin.getHashAlgorithm()
    /// ```
  @JavaMethod
  open func getHashAlgorithm() -> String

    /// Java method `matchesHostname`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.CertificatePinner$Pin.matchesHostname(java.lang.String)
    /// ```
  @JavaMethod
  open func matchesHostname(_ arg0: String) -> Bool

    /// Java method `getPattern`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.CertificatePinner$Pin.getPattern()
    /// ```
  @JavaMethod
  open func getPattern() -> String

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean okhttp3.CertificatePinner$Pin.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String okhttp3.CertificatePinner$Pin.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int okhttp3.CertificatePinner$Pin.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32
  }
}
#endif
