// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("okhttp3.Connection")
public struct Connection {
  /// Java method `route`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract okhttp3.Route okhttp3.Connection.route()
  /// ```
@JavaMethod
  public func route() -> Route!

  /// Java method `handshake`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract okhttp3.Handshake okhttp3.Connection.handshake()
  /// ```
@JavaMethod
  public func handshake() -> Handshake!
}
#endif
