// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Cookie {
  @JavaClass("okhttp3.Cookie$Companion")
  open class Companion: JavaObject {
    /// Java method `parseAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Cookie> okhttp3.Cookie$Companion.parseAll(okhttp3.HttpUrl,okhttp3.Headers)
    /// ```
  @JavaMethod
  open func parseAll(_ arg0: HttpUrl?, _ arg1: Headers?) -> List<Cookie>!

    /// Java method `parse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie okhttp3.Cookie$Companion.parse$okhttp(long,okhttp3.HttpUrl,java.lang.String)
    /// ```
  @JavaMethod
  open func parse$okhttp(_ arg0: Int64, _ arg1: HttpUrl?, _ arg2: String) -> Cookie!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cookie okhttp3.Cookie$Companion.parse(okhttp3.HttpUrl,java.lang.String)
    /// ```
  @JavaMethod
  open func parse(_ arg0: HttpUrl?, _ arg1: String) -> Cookie!
  }
}
extension JavaClass<Cookie.Companion> {
  /// Java method `access$domainMatch`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static final boolean okhttp3.Cookie$Companion.access$domainMatch(okhttp3.Cookie$Companion,java.lang.String,java.lang.String)
  /// ```
@JavaStaticMethod
  public func access$domainMatch(_ arg0: Cookie.Companion?, _ arg1: String, _ arg2: String) -> Bool

  /// Java method `access$pathMatch`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static final boolean okhttp3.Cookie$Companion.access$pathMatch(okhttp3.Cookie$Companion,okhttp3.HttpUrl,java.lang.String)
  /// ```
@JavaStaticMethod
  public func access$pathMatch(_ arg0: Cookie.Companion?, _ arg1: HttpUrl?, _ arg2: String) -> Bool
}
#endif
