// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.Credentials")
open class Credentials: JavaObject {

}
extension JavaClass<Credentials> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: Credentials!

    /// Java method `basic$default`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.lang.String okhttp3.Credentials.basic$default(java.lang.String,java.lang.String,java.nio.charset.Charset,int,java.lang.Object)
    /// ```
  @JavaStaticMethod
  public func basic$default(_ arg0: String, _ arg1: String, _ arg2: Charset?, _ arg3: Int32, _ arg4: JavaObject?) -> String

    /// Java method `basic`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final java.lang.String okhttp3.Credentials.basic(java.lang.String,java.lang.String)
    /// ```
  @JavaStaticMethod
  public func basic(_ arg0: String, _ arg1: String) -> String

    /// Java method `basic`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final java.lang.String okhttp3.Credentials.basic(java.lang.String,java.lang.String,java.nio.charset.Charset)
    /// ```
  @JavaStaticMethod
  public func basic(_ arg0: String, _ arg1: String, _ arg2: Charset?) -> String
}
#endif
