// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension FormBody {
  @JavaClass("okhttp3.FormBody$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Charset?, environment: JNIEnvironment? = nil)

    /// Java method `addEncoded`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.FormBody$Builder okhttp3.FormBody$Builder.addEncoded(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addEncoded(_ arg0: String, _ arg1: String) -> FormBody.Builder!

    /// Java method `add`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.FormBody$Builder okhttp3.FormBody$Builder.add(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func add(_ arg0: String, _ arg1: String) -> FormBody.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.FormBody okhttp3.FormBody$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> FormBody!
  }
}
#endif
