// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Handshake {
  @JavaClass("okhttp3.Handshake$Companion")
  open class Companion: JavaObject {

  }
}
#endif
