// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.Headers")
open class Headers: JavaObject {
  /// Java method `-deprecated_size`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final int okhttp3.Headers.-deprecated_size()
  /// ```
@JavaMethod("-deprecated_size")
  open func `-deprecated_size`() -> Int32

  /// Java method `byteCount`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final long okhttp3.Headers.byteCount()
  /// ```
@JavaMethod
  open func byteCount() -> Int64

  /// Java method `newBuilder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Headers$Builder okhttp3.Headers.newBuilder()
  /// ```
@JavaMethod
  open func newBuilder() -> Headers.Builder!

  /// Java method `name`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Headers.name(int)
  /// ```
@JavaMethod
  open func name(_ arg0: Int32) -> String

  /// Java method `size`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final int okhttp3.Headers.size()
  /// ```
@JavaMethod
  open func size() -> Int32

  /// Java method `get`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Headers.get(java.lang.String)
  /// ```
@JavaMethod
  open func get(_ arg0: String) -> String

  /// Java method `value`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Headers.value(int)
  /// ```
@JavaMethod
  open func value(_ arg0: Int32) -> String

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean okhttp3.Headers.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String okhttp3.Headers.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `values`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.List<java.lang.String> okhttp3.Headers.values(java.lang.String)
  /// ```
@JavaMethod
  open func values(_ arg0: String) -> List<JavaString>!

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int okhttp3.Headers.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `names`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.Set<java.lang.String> okhttp3.Headers.names()
  /// ```
@JavaMethod
  open func names() -> JavaSet<JavaString>!
}
extension JavaClass<Headers> {
  @JavaStaticField(isFinal: true)
  public var Companion: Headers.Companion!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.Headers okhttp3.Headers.of(java.lang.String...)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: [String]) -> Headers!
}
#endif
