#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension HttpUrl {
  @JavaClass("okhttp3.HttpUrl$Companion")
  open class Companion: JavaObject {
    /// Java method `defaultPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl$Companion.defaultPort(java.lang.String)
    /// ```
  @JavaMethod
  open func defaultPort(_ arg0: String) -> Int32

    /// Java method `toQueryNamesAndValues$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl$Companion.toQueryNamesAndValues$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func toQueryNamesAndValues$okhttp(_ arg0: String) -> List<JavaString>!

    /// Java method `-deprecated_get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.-deprecated_get(java.lang.String)
    /// ```
  @JavaMethod("-deprecated_get")
  open func `-deprecated_get`(_ arg0: String) -> HttpUrl!

    /// Java method `-deprecated_get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.-deprecated_get(java.net.URL)
    /// ```
  @JavaMethod("-deprecated_get")
  open func `-deprecated_get`(_ arg0: JavaURL?) -> HttpUrl!

    /// Java method `-deprecated_parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.-deprecated_parse(java.lang.String)
    /// ```
  @JavaMethod("-deprecated_parse")
  open func `-deprecated_parse`(_ arg0: String) -> HttpUrl!

    /// Java method `percentDecode$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl$Companion.percentDecode$okhttp(java.lang.String,int,int,boolean)
    /// ```
  @JavaMethod
  open func percentDecode$okhttp(_ arg0: String, _ arg1: Int32, _ arg2: Int32, _ arg3: Bool) -> String

    /// Java method `canonicalize$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl$Companion.canonicalize$okhttp(java.lang.String,int,int,java.lang.String,boolean,boolean,boolean,boolean,java.nio.charset.Charset)
    /// ```
  @JavaMethod
  open func canonicalize$okhttp(_ arg0: String, _ arg1: Int32, _ arg2: Int32, _ arg3: String, _ arg4: Bool, _ arg5: Bool, _ arg6: Bool, _ arg7: Bool, _ arg8: Charset?) -> String

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.get(java.lang.String)
    /// ```
  @JavaMethod
  open func get(_ arg0: String) -> HttpUrl!

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.get(java.net.URL)
    /// ```
  @JavaMethod
  open func get(_ arg0: JavaURL?) -> HttpUrl!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl$Companion.parse(java.lang.String)
    /// ```
  @JavaMethod
  open func parse(_ arg0: String) -> HttpUrl!
  }
}
extension JavaClass<HttpUrl.Companion> {
  /// Java method `canonicalize$okhttp$default`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String okhttp3.HttpUrl$Companion.canonicalize$okhttp$default(okhttp3.HttpUrl$Companion,java.lang.String,int,int,java.lang.String,boolean,boolean,boolean,boolean,java.nio.charset.Charset,int,java.lang.Object)
  /// ```
@JavaStaticMethod
  public func canonicalize$okhttp$default(_ arg0: HttpUrl.Companion?, _ arg1: String, _ arg2: Int32, _ arg3: Int32, _ arg4: String, _ arg5: Bool, _ arg6: Bool, _ arg7: Bool, _ arg8: Bool, _ arg9: Charset?, _ arg10: Int32, _ arg11: JavaObject?) -> String

  /// Java method `percentDecode$okhttp$default`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String okhttp3.HttpUrl$Companion.percentDecode$okhttp$default(okhttp3.HttpUrl$Companion,java.lang.String,int,int,boolean,int,java.lang.Object)
  /// ```
@JavaStaticMethod
  public func percentDecode$okhttp$default(_ arg0: HttpUrl.Companion?, _ arg1: String, _ arg2: Int32, _ arg3: Int32, _ arg4: Bool, _ arg5: Int32, _ arg6: JavaObject?) -> String
}
#endif
