#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Interceptor {
  @JavaInterface("okhttp3.Interceptor$Chain")
  public struct Chain {
    /// Java method `connectTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract int okhttp3.Interceptor$Chain.connectTimeoutMillis()
    /// ```
  @JavaMethod
  public func connectTimeoutMillis() -> Int32

    /// Java method `proceed`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract okhttp3.Response okhttp3.Interceptor$Chain.proceed(okhttp3.Request) throws java.io.IOException
    /// ```
  @JavaMethod
  public func proceed(_ arg0: Request?) throws -> Response!

    /// Java method `readTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract int okhttp3.Interceptor$Chain.readTimeoutMillis()
    /// ```
  @JavaMethod
  public func readTimeoutMillis() -> Int32

    /// Java method `writeTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract int okhttp3.Interceptor$Chain.writeTimeoutMillis()
    /// ```
  @JavaMethod
  public func writeTimeoutMillis() -> Int32

    /// Java method `call`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract okhttp3.Call okhttp3.Interceptor$Chain.call()
    /// ```
  @JavaMethod
  public func call() -> Call!

    /// Java method `request`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract okhttp3.Request okhttp3.Interceptor$Chain.request()
    /// ```
  @JavaMethod
  public func request() -> Request!

    /// Java method `connection`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract okhttp3.Connection okhttp3.Interceptor$Chain.connection()
    /// ```
  @JavaMethod
  public func connection() -> Connection!
  }
}
#endif
