// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension MultipartBody {
  @JavaClass("okhttp3.MultipartBody$Companion")
  open class Companion: JavaObject {

  }
}
#endif
