#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension MultipartBody {
  @JavaClass("okhttp3.MultipartBody$Part")
  open class Part: JavaObject {
    /// Java method `headers`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers okhttp3.MultipartBody$Part.headers()
    /// ```
  @JavaMethod
  open func headers() -> Headers!

    /// Java method `-deprecated_body`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.MultipartBody$Part.-deprecated_body()
    /// ```
  @JavaMethod("-deprecated_body")
  open func `-deprecated_body`() -> RequestBody!

    /// Java method `-deprecated_headers`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers okhttp3.MultipartBody$Part.-deprecated_headers()
    /// ```
  @JavaMethod("-deprecated_headers")
  open func `-deprecated_headers`() -> Headers!

    /// Java method `body`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.RequestBody okhttp3.MultipartBody$Part.body()
    /// ```
  @JavaMethod
  open func body() -> RequestBody!
  }
}
extension JavaClass<MultipartBody.Part> {
  @JavaStaticField(isFinal: true)
  public var Companion: MultipartBody.Part.Companion!

    /// Java method `createFormData`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.MultipartBody$Part okhttp3.MultipartBody$Part.createFormData(java.lang.String,java.lang.String,okhttp3.RequestBody)
    /// ```
  @JavaStaticMethod
  public func createFormData(_ arg0: String, _ arg1: String, _ arg2: RequestBody?) -> MultipartBody.Part!

    /// Java method `createFormData`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.MultipartBody$Part okhttp3.MultipartBody$Part.createFormData(java.lang.String,java.lang.String)
    /// ```
  @JavaStaticMethod
  public func createFormData(_ arg0: String, _ arg1: String) -> MultipartBody.Part!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.MultipartBody$Part okhttp3.MultipartBody$Part.create(okhttp3.RequestBody)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: RequestBody?) -> MultipartBody.Part!

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.MultipartBody$Part okhttp3.MultipartBody$Part.create(okhttp3.Headers,okhttp3.RequestBody)
    /// ```
  @JavaStaticMethod
  public func create(_ arg0: Headers?, _ arg1: RequestBody?) -> MultipartBody.Part!
}
#endif
