// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension OkHttpClient {
  @JavaClass("okhttp3.OkHttpClient$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: OkHttpClient?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `setMinWebSocketMessageToCompress$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setMinWebSocketMessageToCompress$okhttp(long)
    /// ```
  @JavaMethod
  open func setMinWebSocketMessageToCompress$okhttp(_ arg0: Int64)

    /// Java method `getMinWebSocketMessageToCompress$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final long okhttp3.OkHttpClient$Builder.getMinWebSocketMessageToCompress$okhttp()
    /// ```
  @JavaMethod
  open func getMinWebSocketMessageToCompress$okhttp() -> Int64

    /// Java method `setDispatcher$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setDispatcher$okhttp(okhttp3.Dispatcher)
    /// ```
  @JavaMethod
  open func setDispatcher$okhttp(_ arg0: Dispatcher?)

    /// Java method `setConnectionPool$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setConnectionPool$okhttp(okhttp3.ConnectionPool)
    /// ```
  @JavaMethod
  open func setConnectionPool$okhttp(_ arg0: ConnectionPool?)

    /// Java method `setEventListenerFactory$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setEventListenerFactory$okhttp(okhttp3.EventListener$Factory)
    /// ```
  @JavaMethod
  open func setEventListenerFactory$okhttp(_ arg0: EventListener.Factory?)

    /// Java method `setRetryOnConnectionFailure$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setRetryOnConnectionFailure$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setRetryOnConnectionFailure$okhttp(_ arg0: Bool)

    /// Java method `setAuthenticator$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setAuthenticator$okhttp(okhttp3.Authenticator)
    /// ```
  @JavaMethod
  open func setAuthenticator$okhttp(_ arg0: Authenticator?)

    /// Java method `setFollowRedirects$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setFollowRedirects$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setFollowRedirects$okhttp(_ arg0: Bool)

    /// Java method `setFollowSslRedirects$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setFollowSslRedirects$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setFollowSslRedirects$okhttp(_ arg0: Bool)

    /// Java method `setCookieJar$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setCookieJar$okhttp(okhttp3.CookieJar)
    /// ```
  @JavaMethod
  open func setCookieJar$okhttp(_ arg0: CookieJar?)

    /// Java method `setProxyAuthenticator$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setProxyAuthenticator$okhttp(okhttp3.Authenticator)
    /// ```
  @JavaMethod
  open func setProxyAuthenticator$okhttp(_ arg0: Authenticator?)

    /// Java method `setConnectionSpecs$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setConnectionSpecs$okhttp(java.util.List<okhttp3.ConnectionSpec>)
    /// ```
  @JavaMethod
  open func setConnectionSpecs$okhttp(_ arg0: List<ConnectionSpec>?)

    /// Java method `setCertificatePinner$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setCertificatePinner$okhttp(okhttp3.CertificatePinner)
    /// ```
  @JavaMethod
  open func setCertificatePinner$okhttp(_ arg0: CertificatePinner?)

    /// Java method `setCallTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setCallTimeout$okhttp(int)
    /// ```
  @JavaMethod
  open func setCallTimeout$okhttp(_ arg0: Int32)

    /// Java method `setConnectTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setConnectTimeout$okhttp(int)
    /// ```
  @JavaMethod
  open func setConnectTimeout$okhttp(_ arg0: Int32)

    /// Java method `setReadTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setReadTimeout$okhttp(int)
    /// ```
  @JavaMethod
  open func setReadTimeout$okhttp(_ arg0: Int32)

    /// Java method `setWriteTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setWriteTimeout$okhttp(int)
    /// ```
  @JavaMethod
  open func setWriteTimeout$okhttp(_ arg0: Int32)

    /// Java method `setPingInterval$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setPingInterval$okhttp(int)
    /// ```
  @JavaMethod
  open func setPingInterval$okhttp(_ arg0: Int32)

    /// Java method `addNetworkInterceptor`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.addNetworkInterceptor(okhttp3.Interceptor)
    /// ```
  @JavaMethod
  open func addNetworkInterceptor(_ arg0: Interceptor?) -> OkHttpClient.Builder!

    /// Java method `getDispatcher$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Dispatcher okhttp3.OkHttpClient$Builder.getDispatcher$okhttp()
    /// ```
  @JavaMethod
  open func getDispatcher$okhttp() -> Dispatcher!

    /// Java method `getConnectionPool$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionPool okhttp3.OkHttpClient$Builder.getConnectionPool$okhttp()
    /// ```
  @JavaMethod
  open func getConnectionPool$okhttp() -> ConnectionPool!

    /// Java method `getInterceptors$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient$Builder.getInterceptors$okhttp()
    /// ```
  @JavaMethod
  open func getInterceptors$okhttp() -> List<Interceptor>!

    /// Java method `getNetworkInterceptors$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient$Builder.getNetworkInterceptors$okhttp()
    /// ```
  @JavaMethod
  open func getNetworkInterceptors$okhttp() -> List<Interceptor>!

    /// Java method `networkInterceptors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient$Builder.networkInterceptors()
    /// ```
  @JavaMethod
  open func networkInterceptors() -> List<Interceptor>!

    /// Java method `getEventListenerFactory$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.EventListener$Factory okhttp3.OkHttpClient$Builder.getEventListenerFactory$okhttp()
    /// ```
  @JavaMethod
  open func getEventListenerFactory$okhttp() -> EventListener.Factory!

    /// Java method `eventListenerFactory`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.eventListenerFactory(okhttp3.EventListener$Factory)
    /// ```
  @JavaMethod
  open func eventListenerFactory(_ arg0: EventListener.Factory?) -> OkHttpClient.Builder!

    /// Java method `getRetryOnConnectionFailure$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient$Builder.getRetryOnConnectionFailure$okhttp()
    /// ```
  @JavaMethod
  open func getRetryOnConnectionFailure$okhttp() -> Bool

    /// Java method `retryOnConnectionFailure`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.retryOnConnectionFailure(boolean)
    /// ```
  @JavaMethod
  open func retryOnConnectionFailure(_ arg0: Bool) -> OkHttpClient.Builder!

    /// Java method `getAuthenticator$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Authenticator okhttp3.OkHttpClient$Builder.getAuthenticator$okhttp()
    /// ```
  @JavaMethod
  open func getAuthenticator$okhttp() -> Authenticator!

    /// Java method `getFollowRedirects$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient$Builder.getFollowRedirects$okhttp()
    /// ```
  @JavaMethod
  open func getFollowRedirects$okhttp() -> Bool

    /// Java method `getFollowSslRedirects$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient$Builder.getFollowSslRedirects$okhttp()
    /// ```
  @JavaMethod
  open func getFollowSslRedirects$okhttp() -> Bool

    /// Java method `getCookieJar$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CookieJar okhttp3.OkHttpClient$Builder.getCookieJar$okhttp()
    /// ```
  @JavaMethod
  open func getCookieJar$okhttp() -> CookieJar!

    /// Java method `dispatcher`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.dispatcher(okhttp3.Dispatcher)
    /// ```
  @JavaMethod
  open func dispatcher(_ arg0: Dispatcher?) -> OkHttpClient.Builder!

    /// Java method `connectionPool`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.connectionPool(okhttp3.ConnectionPool)
    /// ```
  @JavaMethod
  open func connectionPool(_ arg0: ConnectionPool?) -> OkHttpClient.Builder!

    /// Java method `interceptors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient$Builder.interceptors()
    /// ```
  @JavaMethod
  open func interceptors() -> List<Interceptor>!

    /// Java method `authenticator`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.authenticator(okhttp3.Authenticator)
    /// ```
  @JavaMethod
  open func authenticator(_ arg0: Authenticator?) -> OkHttpClient.Builder!

    /// Java method `followRedirects`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.followRedirects(boolean)
    /// ```
  @JavaMethod
  open func followRedirects(_ arg0: Bool) -> OkHttpClient.Builder!

    /// Java method `followSslRedirects`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.followSslRedirects(boolean)
    /// ```
  @JavaMethod
  open func followSslRedirects(_ arg0: Bool) -> OkHttpClient.Builder!

    /// Java method `cookieJar`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.cookieJar(okhttp3.CookieJar)
    /// ```
  @JavaMethod
  open func cookieJar(_ arg0: CookieJar?) -> OkHttpClient.Builder!

    /// Java method `getCache$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cache okhttp3.OkHttpClient$Builder.getCache$okhttp()
    /// ```
  @JavaMethod
  open func getCache$okhttp() -> Cache!

    /// Java method `getDns$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Dns okhttp3.OkHttpClient$Builder.getDns$okhttp()
    /// ```
  @JavaMethod
  open func getDns$okhttp() -> Dns!

    /// Java method `dns`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.dns(okhttp3.Dns)
    /// ```
  @JavaMethod
  open func dns(_ arg0: Dns?) -> OkHttpClient.Builder!

    /// Java method `proxyAuthenticator`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.proxyAuthenticator(okhttp3.Authenticator)
    /// ```
  @JavaMethod
  open func proxyAuthenticator(_ arg0: Authenticator?) -> OkHttpClient.Builder!

    /// Java method `connectionSpecs`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.connectionSpecs(java.util.List<okhttp3.ConnectionSpec>)
    /// ```
  @JavaMethod
  open func connectionSpecs(_ arg0: List<ConnectionSpec>?) -> OkHttpClient.Builder!

    /// Java method `certificatePinner`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.certificatePinner(okhttp3.CertificatePinner)
    /// ```
  @JavaMethod
  open func certificatePinner(_ arg0: CertificatePinner?) -> OkHttpClient.Builder!

    /// Java method `getProxyAuthenticator$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Authenticator okhttp3.OkHttpClient$Builder.getProxyAuthenticator$okhttp()
    /// ```
  @JavaMethod
  open func getProxyAuthenticator$okhttp() -> Authenticator!

    /// Java method `getConnectionSpecs$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.ConnectionSpec> okhttp3.OkHttpClient$Builder.getConnectionSpecs$okhttp()
    /// ```
  @JavaMethod
  open func getConnectionSpecs$okhttp() -> List<ConnectionSpec>!

    /// Java method `getCallTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient$Builder.getCallTimeout$okhttp()
    /// ```
  @JavaMethod
  open func getCallTimeout$okhttp() -> Int32

    /// Java method `getConnectTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient$Builder.getConnectTimeout$okhttp()
    /// ```
  @JavaMethod
  open func getConnectTimeout$okhttp() -> Int32

    /// Java method `getReadTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient$Builder.getReadTimeout$okhttp()
    /// ```
  @JavaMethod
  open func getReadTimeout$okhttp() -> Int32

    /// Java method `getWriteTimeout$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient$Builder.getWriteTimeout$okhttp()
    /// ```
  @JavaMethod
  open func getWriteTimeout$okhttp() -> Int32

    /// Java method `getPingInterval$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient$Builder.getPingInterval$okhttp()
    /// ```
  @JavaMethod
  open func getPingInterval$okhttp() -> Int32

    /// Java method `minWebSocketMessageToCompress`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.minWebSocketMessageToCompress(long)
    /// ```
  @JavaMethod
  open func minWebSocketMessageToCompress(_ arg0: Int64) -> OkHttpClient.Builder!

    /// Java method `getCertificatePinner$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CertificatePinner okhttp3.OkHttpClient$Builder.getCertificatePinner$okhttp()
    /// ```
  @JavaMethod
  open func getCertificatePinner$okhttp() -> CertificatePinner!

    /// Java method `setCache$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setCache$okhttp(okhttp3.Cache)
    /// ```
  @JavaMethod
  open func setCache$okhttp(_ arg0: Cache?)

    /// Java method `setDns$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.OkHttpClient$Builder.setDns$okhttp(okhttp3.Dns)
    /// ```
  @JavaMethod
  open func setDns$okhttp(_ arg0: Dns?)

    /// Java method `addInterceptor`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.addInterceptor(okhttp3.Interceptor)
    /// ```
  @JavaMethod
  open func addInterceptor(_ arg0: Interceptor?) -> OkHttpClient.Builder!

    /// Java method `eventListener`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.eventListener(okhttp3.EventListener)
    /// ```
  @JavaMethod
  open func eventListener(_ arg0: EventListener?) -> OkHttpClient.Builder!

    /// Java method `cache`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.cache(okhttp3.Cache)
    /// ```
  @JavaMethod
  open func cache(_ arg0: Cache?) -> OkHttpClient.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.OkHttpClient okhttp3.OkHttpClient$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> OkHttpClient!
  }
}
#endif
