// swift-format-ignore-file
#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension ResponseBody {
  @JavaClass("okhttp3.ResponseBody$BomAwareReader")
  open class BomAwareReader: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: BufferedSource?, _ arg1: Charset?, environment: JNIEnvironment? = nil)

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.ResponseBody$BomAwareReader.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open func close() throws

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int okhttp3.ResponseBody$BomAwareReader.read(char[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func read(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws -> Int32
  }
}
#endif
