#if OkHttp4
// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.WebSocketListener")
open class WebSocketListener: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `onOpen`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.WebSocketListener.onOpen(okhttp3.WebSocket,okhttp3.Response)
    /// ```
  @JavaMethod
  open func onOpen(_ arg0: WebSocket?, _ arg1: Response?)

    /// Java method `onMessage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.WebSocketListener.onMessage(okhttp3.WebSocket,java.lang.String)
    /// ```
  @JavaMethod
  open func onMessage(_ arg0: WebSocket?, _ arg1: String)

    /// Java method `onClosing`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.WebSocketListener.onClosing(okhttp3.WebSocket,int,java.lang.String)
    /// ```
  @JavaMethod
  open func onClosing(_ arg0: WebSocket?, _ arg1: Int32, _ arg2: String)

    /// Java method `onClosed`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.WebSocketListener.onClosed(okhttp3.WebSocket,int,java.lang.String)
    /// ```
  @JavaMethod
  open func onClosed(_ arg0: WebSocket?, _ arg1: Int32, _ arg2: String)

    /// Java method `onFailure`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.WebSocketListener.onFailure(okhttp3.WebSocket,java.lang.Throwable,okhttp3.Response)
    /// ```
  @JavaMethod
  open func onFailure(_ arg0: WebSocket?, _ arg1: Throwable?, _ arg2: Response?)
}
#endif
