// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension Authenticator {
  @JavaClass("okhttp3.Authenticator$Companion")
  open class Companion: JavaObject {

  }
}
