// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Authenticator {
    @JavaClass("okhttp3.Authenticator$Companion")
    open class Companion: JavaObject {

    }
}
