// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("okio.BufferedSource")
public struct BufferedSource {
  /// Java method `readUtf8LineStrict`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String okio.BufferedSource.readUtf8LineStrict() throws java.io.IOException
  /// ```
@JavaMethod
  public func readUtf8LineStrict() throws -> String

  /// Java method `readUtf8LineStrict`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String okio.BufferedSource.readUtf8LineStrict(long) throws java.io.IOException
  /// ```
@JavaMethod
  public func readUtf8LineStrict(_ arg0: Int64) throws -> String

  /// Java method `exhausted`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean okio.BufferedSource.exhausted() throws java.io.IOException
  /// ```
@JavaMethod
  public func exhausted() throws -> Bool

  /// Java method `inputStream`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.io.InputStream okio.BufferedSource.inputStream()
  /// ```
@JavaMethod
  public func inputStream() -> InputStream!

  /// Java method `require`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void okio.BufferedSource.require(long) throws java.io.IOException
  /// ```
@JavaMethod
  public func require(_ arg0: Int64) throws

  /// Java method `readShortLe`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract short okio.BufferedSource.readShortLe() throws java.io.IOException
  /// ```
@JavaMethod
  public func readShortLe() throws -> Int16

  /// Java method `readIntLe`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int okio.BufferedSource.readIntLe() throws java.io.IOException
  /// ```
@JavaMethod
  public func readIntLe() throws -> Int32

  /// Java method `readLongLe`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long okio.BufferedSource.readLongLe() throws java.io.IOException
  /// ```
@JavaMethod
  public func readLongLe() throws -> Int64

  /// Java method `readDecimalLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long okio.BufferedSource.readDecimalLong() throws java.io.IOException
  /// ```
@JavaMethod
  public func readDecimalLong() throws -> Int64

  /// Java method `readByteArray`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract byte[] okio.BufferedSource.readByteArray(long) throws java.io.IOException
  /// ```
@JavaMethod
  public func readByteArray(_ arg0: Int64) throws -> [Int8]

  /// Java method `readByteArray`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract byte[] okio.BufferedSource.readByteArray() throws java.io.IOException
  /// ```
@JavaMethod
  public func readByteArray() throws -> [Int8]

  /// Java method `readUtf8`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String okio.BufferedSource.readUtf8() throws java.io.IOException
  /// ```
@JavaMethod
  public func readUtf8() throws -> String

  /// Java method `readUtf8`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String okio.BufferedSource.readUtf8(long) throws java.io.IOException
  /// ```
@JavaMethod
  public func readUtf8(_ arg0: Int64) throws -> String

  /// Java method `readUtf8Line`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String okio.BufferedSource.readUtf8Line() throws java.io.IOException
  /// ```
@JavaMethod
  public func readUtf8Line() throws -> String

  /// Java method `readUtf8CodePoint`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int okio.BufferedSource.readUtf8CodePoint() throws java.io.IOException
  /// ```
@JavaMethod
  public func readUtf8CodePoint() throws -> Int32

  /// Java method `readHexadecimalUnsignedLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long okio.BufferedSource.readHexadecimalUnsignedLong() throws java.io.IOException
  /// ```
@JavaMethod
  public func readHexadecimalUnsignedLong() throws -> Int64

  /// Java method `indexOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long okio.BufferedSource.indexOf(byte,long,long) throws java.io.IOException
  /// ```
@JavaMethod
  public func indexOf(_ arg0: Int8, _ arg1: Int64, _ arg2: Int64) throws -> Int64

  /// Java method `indexOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long okio.BufferedSource.indexOf(byte,long) throws java.io.IOException
  /// ```
@JavaMethod
  public func indexOf(_ arg0: Int8, _ arg1: Int64) throws -> Int64

  /// Java method `indexOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long okio.BufferedSource.indexOf(byte) throws java.io.IOException
  /// ```
@JavaMethod
  public func indexOf(_ arg0: Int8) throws -> Int64

  /// Java method `readInt`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int okio.BufferedSource.readInt() throws java.io.IOException
  /// ```
@JavaMethod
  public func readInt() throws -> Int32

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int okio.BufferedSource.read(byte[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  public func read(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws -> Int32

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int okio.BufferedSource.read(byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  public func read(_ arg0: [Int8]) throws -> Int32

  /// Java method `skip`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void okio.BufferedSource.skip(long) throws java.io.IOException
  /// ```
@JavaMethod
  public func skip(_ arg0: Int64) throws

  /// Java method `peek`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract okio.BufferedSource okio.BufferedSource.peek()
  /// ```
@JavaMethod
  public func peek() -> BufferedSource!

  /// Java method `readLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long okio.BufferedSource.readLong() throws java.io.IOException
  /// ```
@JavaMethod
  public func readLong() throws -> Int64

  /// Java method `readByte`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract byte okio.BufferedSource.readByte() throws java.io.IOException
  /// ```
@JavaMethod
  public func readByte() throws -> Int8

  /// Java method `readShort`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract short okio.BufferedSource.readShort() throws java.io.IOException
  /// ```
@JavaMethod
  public func readShort() throws -> Int16

  /// Java method `readFully`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void okio.BufferedSource.readFully(byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  public func readFully(_ arg0: [Int8]) throws

  /// Java method `readString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String okio.BufferedSource.readString(long,java.nio.charset.Charset) throws java.io.IOException
  /// ```
@JavaMethod
  public func readString(_ arg0: Int64, _ arg1: Charset?) throws -> String

  /// Java method `readString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String okio.BufferedSource.readString(java.nio.charset.Charset) throws java.io.IOException
  /// ```
@JavaMethod
  public func readString(_ arg0: Charset?) throws -> String

  /// Java method `request`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean okio.BufferedSource.request(long) throws java.io.IOException
  /// ```
@JavaMethod
  public func request(_ arg0: Int64) throws -> Bool

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void okio.Source.close() throws java.io.IOException
  /// ```
@JavaMethod
  public func close() throws

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.nio.channels.ReadableByteChannel.read(java.nio.ByteBuffer) throws java.io.IOException
  /// ```
@JavaMethod
  public func read(_ arg0: ByteBuffer?) throws -> Int32

  /// Java method `isOpen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.channels.Channel.isOpen()
  /// ```
@JavaMethod
  public func isOpen() -> Bool
}
