// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension CacheControl {
    @JavaClass("okhttp3.CacheControl$Companion")
    open class Companion: JavaObject {
        /// Java method `parse`.
        ///
        /// ### Java method signature
        /// ```java
        /// public final okhttp3.CacheControl okhttp3.CacheControl$Companion.parse(okhttp3.Headers)
        /// ```
        @JavaMethod
        open func parse(_ arg0: Headers?) -> CacheControl!
    }
}
