// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension CacheControl {
  @JavaClass("okhttp3.CacheControl$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `noCache`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.noCache()
    /// ```
  @JavaMethod
  open func noCache() -> CacheControl.Builder!

    /// Java method `noStore`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.noStore()
    /// ```
  @JavaMethod
  open func noStore() -> CacheControl.Builder!

    /// Java method `onlyIfCached`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.onlyIfCached()
    /// ```
  @JavaMethod
  open func onlyIfCached() -> CacheControl.Builder!

    /// Java method `noTransform`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.noTransform()
    /// ```
  @JavaMethod
  open func noTransform() -> CacheControl.Builder!

    /// Java method `immutable`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl$Builder okhttp3.CacheControl$Builder.immutable()
    /// ```
  @JavaMethod
  open func immutable() -> CacheControl.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CacheControl okhttp3.CacheControl$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> CacheControl!
  }
}
