// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension CertificatePinner {
  @JavaClass("okhttp3.CertificatePinner$Companion")
  open class Companion: JavaObject {

  }
}
