// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("okhttp3.Challenge")
open class Challenge: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

    /// Java method `-deprecated_charset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.nio.charset.Charset okhttp3.Challenge.-deprecated_charset()
    /// ```
  @JavaMethod
  open func `-deprecated_charset`() -> Charset!

    /// Java method `realm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Challenge.realm()
    /// ```
  @JavaMethod
  open func realm() -> String

    /// Java method `withCharset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Challenge okhttp3.Challenge.withCharset(java.nio.charset.Charset)
    /// ```
  @JavaMethod
  open func withCharset(_ arg0: Charset?) -> Challenge!

    /// Java method `-deprecated_scheme`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Challenge.-deprecated_scheme()
    /// ```
  @JavaMethod
  open func `-deprecated_scheme`() -> String

    /// Java method `-deprecated_realm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Challenge.-deprecated_realm()
    /// ```
  @JavaMethod
  open func `-deprecated_realm`() -> String

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean okhttp3.Challenge.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String okhttp3.Challenge.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int okhttp3.Challenge.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `charset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.nio.charset.Charset okhttp3.Challenge.charset()
    /// ```
  @JavaMethod
  open func charset() -> Charset!

    /// Java method `scheme`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Challenge.scheme()
    /// ```
  @JavaMethod
  open func scheme() -> String
}
