// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.ConnectionPool")
open class ConnectionPool: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `evictAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.ConnectionPool.evictAll()
    /// ```
  @JavaMethod
  open func evictAll()

    /// Java method `connectionCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.ConnectionPool.connectionCount()
    /// ```
  @JavaMethod
  open func connectionCount() -> Int32

    /// Java method `idleConnectionCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.ConnectionPool.idleConnectionCount()
    /// ```
  @JavaMethod
  open func idleConnectionCount() -> Int32
}
