// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension ConnectionSpec {
  @JavaClass("okhttp3.ConnectionSpec$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ConnectionSpec?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Bool, environment: JNIEnvironment? = nil)

    /// Java method `getTls$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.ConnectionSpec$Builder.getTls$okhttp()
    /// ```
  @JavaMethod
  open func getTls$okhttp() -> Bool

    /// Java method `setTls$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.ConnectionSpec$Builder.setTls$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setTls$okhttp(_ arg0: Bool)

    /// Java method `cipherSuites`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionSpec$Builder okhttp3.ConnectionSpec$Builder.cipherSuites(okhttp3.CipherSuite...)
    /// ```
  @JavaMethod
  open func cipherSuites(_ arg0: [CipherSuite?]) -> ConnectionSpec.Builder!

    /// Java method `cipherSuites`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionSpec$Builder okhttp3.ConnectionSpec$Builder.cipherSuites(java.lang.String...)
    /// ```
  @JavaMethod
  open func cipherSuites(_ arg0: [String]) -> ConnectionSpec.Builder!

    /// Java method `tlsVersions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionSpec$Builder okhttp3.ConnectionSpec$Builder.tlsVersions(java.lang.String...)
    /// ```
  @JavaMethod
  open func tlsVersions(_ arg0: [String]) -> ConnectionSpec.Builder!

    /// Java method `getCipherSuites$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String[] okhttp3.ConnectionSpec$Builder.getCipherSuites$okhttp()
    /// ```
  @JavaMethod
  open func getCipherSuites$okhttp() -> [String]

    /// Java method `setCipherSuites$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.ConnectionSpec$Builder.setCipherSuites$okhttp(java.lang.String[])
    /// ```
  @JavaMethod
  open func setCipherSuites$okhttp(_ arg0: [String])

    /// Java method `getTlsVersions$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String[] okhttp3.ConnectionSpec$Builder.getTlsVersions$okhttp()
    /// ```
  @JavaMethod
  open func getTlsVersions$okhttp() -> [String]

    /// Java method `setTlsVersions$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.ConnectionSpec$Builder.setTlsVersions$okhttp(java.lang.String[])
    /// ```
  @JavaMethod
  open func setTlsVersions$okhttp(_ arg0: [String])

    /// Java method `getSupportsTlsExtensions$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.ConnectionSpec$Builder.getSupportsTlsExtensions$okhttp()
    /// ```
  @JavaMethod
  open func getSupportsTlsExtensions$okhttp() -> Bool

    /// Java method `supportsTlsExtensions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionSpec$Builder okhttp3.ConnectionSpec$Builder.supportsTlsExtensions(boolean)
    /// ```
  @JavaMethod
  open func supportsTlsExtensions(_ arg0: Bool) -> ConnectionSpec.Builder!

    /// Java method `setSupportsTlsExtensions$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.ConnectionSpec$Builder.setSupportsTlsExtensions$okhttp(boolean)
    /// ```
  @JavaMethod
  open func setSupportsTlsExtensions$okhttp(_ arg0: Bool)

    /// Java method `allEnabledCipherSuites`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionSpec$Builder okhttp3.ConnectionSpec$Builder.allEnabledCipherSuites()
    /// ```
  @JavaMethod
  open func allEnabledCipherSuites() -> ConnectionSpec.Builder!

    /// Java method `allEnabledTlsVersions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionSpec$Builder okhttp3.ConnectionSpec$Builder.allEnabledTlsVersions()
    /// ```
  @JavaMethod
  open func allEnabledTlsVersions() -> ConnectionSpec.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionSpec okhttp3.ConnectionSpec$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> ConnectionSpec!
  }
}
