// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension ConnectionSpec {
    @JavaClass("okhttp3.ConnectionSpec$Companion")
    open class Companion: JavaObject {

    }
}
