// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("okhttp3.ConnectionSpec")
open class ConnectionSpec: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Bool, _ arg1: Bool, _ arg2: [String], _ arg3: [String], environment: JNIEnvironment? = nil)

    /// Java method `supportsTlsExtensions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.ConnectionSpec.supportsTlsExtensions()
    /// ```
  @JavaMethod
  open func supportsTlsExtensions() -> Bool

    /// Java method `-deprecated_cipherSuites`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.CipherSuite> okhttp3.ConnectionSpec.-deprecated_cipherSuites()
    /// ```
  @JavaMethod
  open func `-deprecated_cipherSuites`() -> List<CipherSuite>!

    /// Java method `-deprecated_supportsTlsExtensions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.ConnectionSpec.-deprecated_supportsTlsExtensions()
    /// ```
  @JavaMethod
  open func `-deprecated_supportsTlsExtensions`() -> Bool

    /// Java method `cipherSuites`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.CipherSuite> okhttp3.ConnectionSpec.cipherSuites()
    /// ```
  @JavaMethod
  open func cipherSuites() -> List<CipherSuite>!

    /// Java method `isTls`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.ConnectionSpec.isTls()
    /// ```
  @JavaMethod
  open func isTls() -> Bool

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean okhttp3.ConnectionSpec.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String okhttp3.ConnectionSpec.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int okhttp3.ConnectionSpec.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<ConnectionSpec> {
  @JavaStaticField(isFinal: true)
  public var Companion: ConnectionSpec.Companion!

  @JavaStaticField(isFinal: true)
  public var RESTRICTED_TLS: ConnectionSpec!

  @JavaStaticField(isFinal: true)
  public var MODERN_TLS: ConnectionSpec!

  @JavaStaticField(isFinal: true)
  public var COMPATIBLE_TLS: ConnectionSpec!

  @JavaStaticField(isFinal: true)
  public var CLEARTEXT: ConnectionSpec!

    /// Java method `access$getCipherSuitesAsString$p`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final java.lang.String[] okhttp3.ConnectionSpec.access$getCipherSuitesAsString$p(okhttp3.ConnectionSpec)
    /// ```
  @JavaStaticMethod
  public func access$getCipherSuitesAsString$p(_ arg0: ConnectionSpec?) -> [String]

    /// Java method `access$getTlsVersionsAsString$p`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final java.lang.String[] okhttp3.ConnectionSpec.access$getTlsVersionsAsString$p(okhttp3.ConnectionSpec)
    /// ```
  @JavaStaticMethod
  public func access$getTlsVersionsAsString$p(_ arg0: ConnectionSpec?) -> [String]
}
