// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension ConnectionSpec {
  @JavaClass("okhttp3.ConnectionSpec$Companion")
  open class Companion: JavaObject {

  }
}
