// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension CookieJar {
  @JavaClass("okhttp3.CookieJar$Companion")
  open class Companion: JavaObject {

  }
}
