// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("okhttp3.CookieJar")
public struct CookieJar {
    /// Java method `saveFromResponse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void okhttp3.CookieJar.saveFromResponse(okhttp3.HttpUrl,java.util.List<okhttp3.Cookie>)
    /// ```
    @JavaMethod
    public func saveFromResponse(_ arg0: HttpUrl?, _ arg1: List<Cookie>?)

    /// Java method `loadForRequest`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.util.List<okhttp3.Cookie> okhttp3.CookieJar.loadForRequest(okhttp3.HttpUrl)
    /// ```
    @JavaMethod
    public func loadForRequest(_ arg0: HttpUrl?) -> List<Cookie>!
}
extension JavaClass<CookieJar> {
    @JavaStaticField(isFinal: true)
    public var Companion: CookieJar.Companion!

    @JavaStaticField(isFinal: true)
    public var NO_COOKIES: CookieJar!
}
