// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.Cookie")
open class Cookie: JavaObject {
  /// Java method `-deprecated_persistent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.-deprecated_persistent()
  /// ```
@JavaMethod
  open func `-deprecated_persistent`() -> Bool

  /// Java method `-deprecated_expiresAt`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final long okhttp3.Cookie.-deprecated_expiresAt()
  /// ```
@JavaMethod
  open func `-deprecated_expiresAt`() -> Int64

  /// Java method `-deprecated_hostOnly`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.-deprecated_hostOnly()
  /// ```
@JavaMethod
  open func `-deprecated_hostOnly`() -> Bool

  /// Java method `-deprecated_httpOnly`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.-deprecated_httpOnly()
  /// ```
@JavaMethod
  open func `-deprecated_httpOnly`() -> Bool

  /// Java method `expiresAt`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final long okhttp3.Cookie.expiresAt()
  /// ```
@JavaMethod
  open func expiresAt() -> Int64

  /// Java method `domain`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.domain()
  /// ```
@JavaMethod
  open func domain() -> String

  /// Java method `secure`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.secure()
  /// ```
@JavaMethod
  open func secure() -> Bool

  /// Java method `httpOnly`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.httpOnly()
  /// ```
@JavaMethod
  open func httpOnly() -> Bool

  /// Java method `hostOnly`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.hostOnly()
  /// ```
@JavaMethod
  open func hostOnly() -> Bool

  /// Java method `toString$okhttp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.toString$okhttp(boolean)
  /// ```
@JavaMethod
  open func toString$okhttp(_ arg0: Bool) -> String

  /// Java method `-deprecated_name`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.-deprecated_name()
  /// ```
@JavaMethod
  open func `-deprecated_name`() -> String

  /// Java method `-deprecated_value`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.-deprecated_value()
  /// ```
@JavaMethod
  open func `-deprecated_value`() -> String

  /// Java method `-deprecated_domain`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.-deprecated_domain()
  /// ```
@JavaMethod
  open func `-deprecated_domain`() -> String

  /// Java method `-deprecated_path`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.-deprecated_path()
  /// ```
@JavaMethod
  open func `-deprecated_path`() -> String

  /// Java method `-deprecated_secure`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.-deprecated_secure()
  /// ```
@JavaMethod
  open func `-deprecated_secure`() -> Bool

  /// Java method `name`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.name()
  /// ```
@JavaMethod
  open func name() -> String

  /// Java method `value`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.value()
  /// ```
@JavaMethod
  open func value() -> String

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean okhttp3.Cookie.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String okhttp3.Cookie.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int okhttp3.Cookie.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `matches`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.matches(okhttp3.HttpUrl)
  /// ```
@JavaMethod
  open func matches(_ arg0: HttpUrl?) -> Bool

  /// Java method `path`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Cookie.path()
  /// ```
@JavaMethod
  open func path() -> String

  /// Java method `persistent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Cookie.persistent()
  /// ```
@JavaMethod
  open func persistent() -> Bool
}
extension JavaClass<Cookie> {
  @JavaStaticField(isFinal: true)
  public var Companion: Cookie.Companion!

    /// Java method `parseAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final java.util.List<okhttp3.Cookie> okhttp3.Cookie.parseAll(okhttp3.HttpUrl,okhttp3.Headers)
    /// ```
  @JavaStaticMethod
  public func parseAll(_ arg0: HttpUrl?, _ arg1: Headers?) -> List<Cookie>!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.Cookie okhttp3.Cookie.parse(okhttp3.HttpUrl,java.lang.String)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: HttpUrl?, _ arg1: String) -> Cookie!
}
