// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.Dispatcher")
open class Dispatcher: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getMaxRequests`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Dispatcher.getMaxRequests()
    /// ```
  @JavaMethod
  open func getMaxRequests() -> Int32

    /// Java method `setMaxRequests`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Dispatcher.setMaxRequests(int)
    /// ```
  @JavaMethod
  open func setMaxRequests(_ arg0: Int32)

    /// Java method `runningCallsCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Dispatcher.runningCallsCount()
    /// ```
  @JavaMethod
  open func runningCallsCount() -> Int32

    /// Java method `queuedCalls`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized java.util.List<okhttp3.Call> okhttp3.Dispatcher.queuedCalls()
    /// ```
  @JavaMethod
  open func queuedCalls() -> List<Call>!

    /// Java method `runningCalls`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized java.util.List<okhttp3.Call> okhttp3.Dispatcher.runningCalls()
    /// ```
  @JavaMethod
  open func runningCalls() -> List<Call>!

    /// Java method `queuedCallsCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Dispatcher.queuedCallsCount()
    /// ```
  @JavaMethod
  open func queuedCallsCount() -> Int32

    /// Java method `getMaxRequestsPerHost`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized int okhttp3.Dispatcher.getMaxRequestsPerHost()
    /// ```
  @JavaMethod
  open func getMaxRequestsPerHost() -> Int32

    /// Java method `setMaxRequestsPerHost`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Dispatcher.setMaxRequestsPerHost(int)
    /// ```
  @JavaMethod
  open func setMaxRequestsPerHost(_ arg0: Int32)

    /// Java method `cancelAll`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final synchronized void okhttp3.Dispatcher.cancelAll()
    /// ```
  @JavaMethod
  open func cancelAll()
}
