// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("okhttp3.Dns")
public struct Dns {

}
extension JavaClass<Dns> {
  @JavaStaticField(isFinal: true)
  public var Companion: Dns.Companion!

  @JavaStaticField(isFinal: true)
  public var SYSTEM: Dns!
}
