// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension EventListener {
  @JavaClass("okhttp3.EventListener$Companion")
  open class Companion: JavaObject {

  }
}
