// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.EventListener")
open class EventListener: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `callStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.callStart(okhttp3.Call)
    /// ```
  @JavaMethod
  open func callStart(_ arg0: Call?)

    /// Java method `proxySelectStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.proxySelectStart(okhttp3.Call,okhttp3.HttpUrl)
    /// ```
  @JavaMethod
  open func proxySelectStart(_ arg0: Call?, _ arg1: HttpUrl?)

    /// Java method `dnsStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.dnsStart(okhttp3.Call,java.lang.String)
    /// ```
  @JavaMethod
  open func dnsStart(_ arg0: Call?, _ arg1: String)

    /// Java method `secureConnectStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.secureConnectStart(okhttp3.Call)
    /// ```
  @JavaMethod
  open func secureConnectStart(_ arg0: Call?)

    /// Java method `secureConnectEnd`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.secureConnectEnd(okhttp3.Call,okhttp3.Handshake)
    /// ```
  @JavaMethod
  open func secureConnectEnd(_ arg0: Call?, _ arg1: Handshake?)

    /// Java method `connectionAcquired`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.connectionAcquired(okhttp3.Call,okhttp3.Connection)
    /// ```
  @JavaMethod
  open func connectionAcquired(_ arg0: Call?, _ arg1: Connection?)

    /// Java method `connectionReleased`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.connectionReleased(okhttp3.Call,okhttp3.Connection)
    /// ```
  @JavaMethod
  open func connectionReleased(_ arg0: Call?, _ arg1: Connection?)

    /// Java method `requestHeadersEnd`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.requestHeadersEnd(okhttp3.Call,okhttp3.Request)
    /// ```
  @JavaMethod
  open func requestHeadersEnd(_ arg0: Call?, _ arg1: Request?)

    /// Java method `requestBodyStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.requestBodyStart(okhttp3.Call)
    /// ```
  @JavaMethod
  open func requestBodyStart(_ arg0: Call?)

    /// Java method `requestBodyEnd`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.requestBodyEnd(okhttp3.Call,long)
    /// ```
  @JavaMethod
  open func requestBodyEnd(_ arg0: Call?, _ arg1: Int64)

    /// Java method `responseHeadersEnd`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.responseHeadersEnd(okhttp3.Call,okhttp3.Response)
    /// ```
  @JavaMethod
  open func responseHeadersEnd(_ arg0: Call?, _ arg1: Response?)

    /// Java method `responseBodyStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.responseBodyStart(okhttp3.Call)
    /// ```
  @JavaMethod
  open func responseBodyStart(_ arg0: Call?)

    /// Java method `responseBodyEnd`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.responseBodyEnd(okhttp3.Call,long)
    /// ```
  @JavaMethod
  open func responseBodyEnd(_ arg0: Call?, _ arg1: Int64)

    /// Java method `callEnd`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.callEnd(okhttp3.Call)
    /// ```
  @JavaMethod
  open func callEnd(_ arg0: Call?)

    /// Java method `canceled`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.canceled(okhttp3.Call)
    /// ```
  @JavaMethod
  open func canceled(_ arg0: Call?)

    /// Java method `cacheHit`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.cacheHit(okhttp3.Call,okhttp3.Response)
    /// ```
  @JavaMethod
  open func cacheHit(_ arg0: Call?, _ arg1: Response?)

    /// Java method `cacheMiss`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.cacheMiss(okhttp3.Call)
    /// ```
  @JavaMethod
  open func cacheMiss(_ arg0: Call?)

    /// Java method `requestHeadersStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.requestHeadersStart(okhttp3.Call)
    /// ```
  @JavaMethod
  open func requestHeadersStart(_ arg0: Call?)

    /// Java method `responseHeadersStart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.responseHeadersStart(okhttp3.Call)
    /// ```
  @JavaMethod
  open func responseHeadersStart(_ arg0: Call?)

    /// Java method `satisfactionFailure`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.satisfactionFailure(okhttp3.Call,okhttp3.Response)
    /// ```
  @JavaMethod
  open func satisfactionFailure(_ arg0: Call?, _ arg1: Response?)

    /// Java method `cacheConditionalHit`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.EventListener.cacheConditionalHit(okhttp3.Call,okhttp3.Response)
    /// ```
  @JavaMethod
  open func cacheConditionalHit(_ arg0: Call?, _ arg1: Response?)
}
extension JavaClass<EventListener> {
  @JavaStaticField(isFinal: true)
  public var Companion: EventListener.Companion!

  @JavaStaticField(isFinal: true)
  public var NONE: EventListener!
}
