// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.FormBody")
open class FormBody: RequestBody {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: List<JavaString>?, _ arg1: List<JavaString>?, environment: JNIEnvironment? = nil)

    /// Java method `contentType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.MediaType okhttp3.FormBody.contentType()
    /// ```
  @JavaMethod
  open override func contentType() -> MediaType!

    /// Java method `contentLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long okhttp3.FormBody.contentLength()
    /// ```
  @JavaMethod
  open override func contentLength() -> Int64

    /// Java method `encodedName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.FormBody.encodedName(int)
    /// ```
  @JavaMethod
  open func encodedName(_ arg0: Int32) -> String

    /// Java method `encodedValue`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.FormBody.encodedValue(int)
    /// ```
  @JavaMethod
  open func encodedValue(_ arg0: Int32) -> String

    /// Java method `-deprecated_size`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.FormBody.-deprecated_size()
    /// ```
  @JavaMethod
  open func `-deprecated_size`() -> Int32

    /// Java method `name`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.FormBody.name(int)
    /// ```
  @JavaMethod
  open func name(_ arg0: Int32) -> String

    /// Java method `size`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.FormBody.size()
    /// ```
  @JavaMethod
  open func size() -> Int32

    /// Java method `value`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.FormBody.value(int)
    /// ```
  @JavaMethod
  open func value(_ arg0: Int32) -> String
}
extension JavaClass<FormBody> {
  @JavaStaticField(isFinal: true)
  public var Companion: FormBody.Companion!
}
