// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension FormBody {
  @JavaClass("okhttp3.FormBody$Companion")
  open class Companion: JavaObject {

  }
}
