// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension Handshake {
  @JavaClass("okhttp3.Handshake$Companion")
  open class Companion: JavaObject {

  }
}
