// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Headers {
    @JavaClass("okhttp3.Headers$Companion")
    open class Companion: JavaObject {
        /// Java method `-deprecated_of`.
        ///
        /// ### Java method signature
        /// ```java
        /// public final okhttp3.Headers okhttp3.Headers$Companion.-deprecated_of(java.lang.String...)
        /// ```
        @JavaMethod
        open func `-deprecated_of`(_ arg0: [String]) -> Headers!

        /// Java method `of`.
        ///
        /// ### Java method signature
        /// ```java
        /// public final okhttp3.Headers okhttp3.Headers$Companion.of(java.lang.String...)
        /// ```
        @JavaMethod
        open func of(_ arg0: [String]) -> Headers!
    }
}
extension JavaClass<Headers.Companion> {
    /// Java method `access$get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final java.lang.String okhttp3.Headers$Companion.access$get(okhttp3.Headers$Companion,java.lang.String[],java.lang.String)
    /// ```
    @JavaStaticMethod
    public func access$get(_ arg0: Headers.Companion?, _ arg1: [String], _ arg2: String) -> String

    /// Java method `access$checkName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final void okhttp3.Headers$Companion.access$checkName(okhttp3.Headers$Companion,java.lang.String)
    /// ```
    @JavaStaticMethod
    public func access$checkName(_ arg0: Headers.Companion?, _ arg1: String)

    /// Java method `access$checkValue`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final void okhttp3.Headers$Companion.access$checkValue(okhttp3.Headers$Companion,java.lang.String,java.lang.String)
    /// ```
    @JavaStaticMethod
    public func access$checkValue(_ arg0: Headers.Companion?, _ arg1: String, _ arg2: String)
}
