// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension HttpUrl.Builder {
    @JavaClass("okhttp3.HttpUrl$Builder$Companion")
    open class Companion: JavaObject {

    }
}
extension JavaClass<HttpUrl.Builder.Companion> {
    /// Java method `access$slashCount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final int okhttp3.HttpUrl$Builder$Companion.access$slashCount(okhttp3.HttpUrl$Builder$Companion,java.lang.String,int,int)
    /// ```
    @JavaStaticMethod
    public func access$slashCount(_ arg0: HttpUrl.Builder.Companion?, _ arg1: String, _ arg2: Int32, _ arg3: Int32)
        -> Int32

    /// Java method `access$parsePort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final int okhttp3.HttpUrl$Builder$Companion.access$parsePort(okhttp3.HttpUrl$Builder$Companion,java.lang.String,int,int)
    /// ```
    @JavaStaticMethod
    public func access$parsePort(_ arg0: HttpUrl.Builder.Companion?, _ arg1: String, _ arg2: Int32, _ arg3: Int32)
        -> Int32

    /// Java method `access$schemeDelimiterOffset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final int okhttp3.HttpUrl$Builder$Companion.access$schemeDelimiterOffset(okhttp3.HttpUrl$Builder$Companion,java.lang.String,int,int)
    /// ```
    @JavaStaticMethod
    public func access$schemeDelimiterOffset(
        _ arg0: HttpUrl.Builder.Companion?, _ arg1: String, _ arg2: Int32, _ arg3: Int32
    ) -> Int32

    /// Java method `access$portColonOffset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final int okhttp3.HttpUrl$Builder$Companion.access$portColonOffset(okhttp3.HttpUrl$Builder$Companion,java.lang.String,int,int)
    /// ```
    @JavaStaticMethod
    public func access$portColonOffset(_ arg0: HttpUrl.Builder.Companion?, _ arg1: String, _ arg2: Int32, _ arg3: Int32)
        -> Int32
}
