// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("okhttp3.HttpUrl")
open class HttpUrl: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: String, _ arg4: Int32, _ arg5: List<JavaString>?, _ arg6: List<JavaString>?, _ arg7: String, _ arg8: String, environment: JNIEnvironment? = nil)

    /// Java method `encodedPathSegments`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl.encodedPathSegments()
    /// ```
  @JavaMethod
  open func encodedPathSegments() -> List<JavaString>!

    /// Java method `queryParameterNames`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.Set<java.lang.String> okhttp3.HttpUrl.queryParameterNames()
    /// ```
  @JavaMethod
  open func queryParameterNames() -> JavaSet<JavaString>!

    /// Java method `queryParameterValues`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl.queryParameterValues(java.lang.String)
    /// ```
  @JavaMethod
  open func queryParameterValues(_ arg0: String) -> List<JavaString>!

    /// Java method `queryParameterValue`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.queryParameterValue(int)
    /// ```
  @JavaMethod
  open func queryParameterValue(_ arg0: Int32) -> String

    /// Java method `-deprecated_encodedUsername`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_encodedUsername()
    /// ```
  @JavaMethod
  open func `-deprecated_encodedUsername`() -> String

    /// Java method `-deprecated_username`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_username()
    /// ```
  @JavaMethod
  open func `-deprecated_username`() -> String

    /// Java method `-deprecated_encodedPassword`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_encodedPassword()
    /// ```
  @JavaMethod
  open func `-deprecated_encodedPassword`() -> String

    /// Java method `-deprecated_password`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_password()
    /// ```
  @JavaMethod
  open func `-deprecated_password`() -> String

    /// Java method `-deprecated_pathSize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl.-deprecated_pathSize()
    /// ```
  @JavaMethod
  open func `-deprecated_pathSize`() -> Int32

    /// Java method `-deprecated_encodedPath`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_encodedPath()
    /// ```
  @JavaMethod
  open func `-deprecated_encodedPath`() -> String

    /// Java method `-deprecated_encodedPathSegments`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl.-deprecated_encodedPathSegments()
    /// ```
  @JavaMethod
  open func `-deprecated_encodedPathSegments`() -> List<JavaString>!

    /// Java method `-deprecated_pathSegments`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl.-deprecated_pathSegments()
    /// ```
  @JavaMethod
  open func `-deprecated_pathSegments`() -> List<JavaString>!

    /// Java method `-deprecated_encodedQuery`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_encodedQuery()
    /// ```
  @JavaMethod
  open func `-deprecated_encodedQuery`() -> String

    /// Java method `-deprecated_querySize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl.-deprecated_querySize()
    /// ```
  @JavaMethod
  open func `-deprecated_querySize`() -> Int32

    /// Java method `-deprecated_queryParameterNames`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.Set<java.lang.String> okhttp3.HttpUrl.-deprecated_queryParameterNames()
    /// ```
  @JavaMethod
  open func `-deprecated_queryParameterNames`() -> JavaSet<JavaString>!

    /// Java method `-deprecated_encodedFragment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_encodedFragment()
    /// ```
  @JavaMethod
  open func `-deprecated_encodedFragment`() -> String

    /// Java method `-deprecated_fragment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_fragment()
    /// ```
  @JavaMethod
  open func `-deprecated_fragment`() -> String

    /// Java method `newBuilder`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl.newBuilder()
    /// ```
  @JavaMethod
  open func newBuilder() -> HttpUrl.Builder!

    /// Java method `newBuilder`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl$Builder okhttp3.HttpUrl.newBuilder(java.lang.String)
    /// ```
  @JavaMethod
  open func newBuilder(_ arg0: String) -> HttpUrl.Builder!

    /// Java method `isHttps`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.HttpUrl.isHttps()
    /// ```
  @JavaMethod
  open func isHttps() -> Bool

    /// Java method `-deprecated_scheme`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_scheme()
    /// ```
  @JavaMethod
  open func `-deprecated_scheme`() -> String

    /// Java method `encodedPath`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.encodedPath()
    /// ```
  @JavaMethod
  open func encodedPath() -> String

    /// Java method `username`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.username()
    /// ```
  @JavaMethod
  open func username() -> String

    /// Java method `password`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.password()
    /// ```
  @JavaMethod
  open func password() -> String

    /// Java method `encodedUsername`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.encodedUsername()
    /// ```
  @JavaMethod
  open func encodedUsername() -> String

    /// Java method `encodedPassword`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.encodedPassword()
    /// ```
  @JavaMethod
  open func encodedPassword() -> String

    /// Java method `encodedFragment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.encodedFragment()
    /// ```
  @JavaMethod
  open func encodedFragment() -> String

    /// Java method `pathSegments`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<java.lang.String> okhttp3.HttpUrl.pathSegments()
    /// ```
  @JavaMethod
  open func pathSegments() -> List<JavaString>!

    /// Java method `encodedQuery`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.encodedQuery()
    /// ```
  @JavaMethod
  open func encodedQuery() -> String

    /// Java method `pathSize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl.pathSize()
    /// ```
  @JavaMethod
  open func pathSize() -> Int32

    /// Java method `querySize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl.querySize()
    /// ```
  @JavaMethod
  open func querySize() -> Int32

    /// Java method `queryParameter`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.queryParameter(java.lang.String)
    /// ```
  @JavaMethod
  open func queryParameter(_ arg0: String) -> String

    /// Java method `queryParameterName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.queryParameterName(int)
    /// ```
  @JavaMethod
  open func queryParameterName(_ arg0: Int32) -> String

    /// Java method `redact`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.redact()
    /// ```
  @JavaMethod
  open func redact() -> String

    /// Java method `topPrivateDomain`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.topPrivateDomain()
    /// ```
  @JavaMethod
  open func topPrivateDomain() -> String

    /// Java method `-deprecated_host`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_host()
    /// ```
  @JavaMethod
  open func `-deprecated_host`() -> String

    /// Java method `-deprecated_port`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl.-deprecated_port()
    /// ```
  @JavaMethod
  open func `-deprecated_port`() -> Int32

    /// Java method `-deprecated_query`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.-deprecated_query()
    /// ```
  @JavaMethod
  open func `-deprecated_query`() -> String

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean okhttp3.HttpUrl.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String okhttp3.HttpUrl.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int okhttp3.HttpUrl.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `resolve`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.HttpUrl okhttp3.HttpUrl.resolve(java.lang.String)
    /// ```
  @JavaMethod
  open func resolve(_ arg0: String) -> HttpUrl!

    /// Java method `port`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.HttpUrl.port()
    /// ```
  @JavaMethod
  open func port() -> Int32

    /// Java method `host`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.host()
    /// ```
  @JavaMethod
  open func host() -> String

    /// Java method `query`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.query()
    /// ```
  @JavaMethod
  open func query() -> String

    /// Java method `scheme`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.scheme()
    /// ```
  @JavaMethod
  open func scheme() -> String

    /// Java method `fragment`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.HttpUrl.fragment()
    /// ```
  @JavaMethod
  open func fragment() -> String
}
extension JavaClass<HttpUrl> {
  @JavaStaticField(isFinal: true)
  public var Companion: HttpUrl.Companion!

  @JavaStaticField(isFinal: true)
  public var USERNAME_ENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var PASSWORD_ENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var PATH_SEGMENT_ENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var PATH_SEGMENT_ENCODE_SET_URI: String

  @JavaStaticField(isFinal: true)
  public var QUERY_ENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var QUERY_COMPONENT_REENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var QUERY_COMPONENT_ENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var QUERY_COMPONENT_ENCODE_SET_URI: String

  @JavaStaticField(isFinal: true)
  public var FORM_ENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var FRAGMENT_ENCODE_SET: String

  @JavaStaticField(isFinal: true)
  public var FRAGMENT_ENCODE_SET_URI: String

    /// Java method `access$getHEX_DIGITS$cp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final char[] okhttp3.HttpUrl.access$getHEX_DIGITS$cp()
    /// ```
  @JavaStaticMethod
  public func access$getHEX_DIGITS$cp() -> [UInt16]

    /// Java method `defaultPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final int okhttp3.HttpUrl.defaultPort(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func defaultPort(_ arg0: String) -> Int32

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.HttpUrl okhttp3.HttpUrl.get(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func get(_ arg0: String) -> HttpUrl!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okhttp3.HttpUrl okhttp3.HttpUrl.parse(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: String) -> HttpUrl!
}
