// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension Interceptor {
  @JavaClass("okhttp3.Interceptor$Companion")
  open class Companion: JavaObject {

  }
}
