// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.MultipartBody")
open class MultipartBody: RequestBody {
  /// Java method `-deprecated_size`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final int okhttp3.MultipartBody.-deprecated_size()
  /// ```
@JavaMethod
  open func `-deprecated_size`() -> Int32

  /// Java method `contentType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public okhttp3.MediaType okhttp3.MultipartBody.contentType()
  /// ```
@JavaMethod
  open override func contentType() -> MediaType!

  /// Java method `contentLength`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long okhttp3.MultipartBody.contentLength() throws java.io.IOException
  /// ```
@JavaMethod
  open override func contentLength() throws -> Int64

  /// Java method `-deprecated_type`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.MediaType okhttp3.MultipartBody.-deprecated_type()
  /// ```
@JavaMethod
  open func `-deprecated_type`() -> MediaType!

  /// Java method `boundary`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.MultipartBody.boundary()
  /// ```
@JavaMethod
  open func boundary() -> String

  /// Java method `-deprecated_boundary`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.MultipartBody.-deprecated_boundary()
  /// ```
@JavaMethod
  open func `-deprecated_boundary`() -> String

  /// Java method `-deprecated_parts`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.List<okhttp3.MultipartBody$Part> okhttp3.MultipartBody.-deprecated_parts()
  /// ```
@JavaMethod
  open func `-deprecated_parts`() -> List<MultipartBody.Part>!

  /// Java method `size`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final int okhttp3.MultipartBody.size()
  /// ```
@JavaMethod
  open func size() -> Int32

  /// Java method `type`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.MediaType okhttp3.MultipartBody.type()
  /// ```
@JavaMethod
  open func type() -> MediaType!

  /// Java method `parts`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.List<okhttp3.MultipartBody$Part> okhttp3.MultipartBody.parts()
  /// ```
@JavaMethod
  open func parts() -> List<MultipartBody.Part>!

  /// Java method `part`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.MultipartBody$Part okhttp3.MultipartBody.part(int)
  /// ```
@JavaMethod
  open func part(_ arg0: Int32) -> MultipartBody.Part!
}
extension JavaClass<MultipartBody> {
  @JavaStaticField(isFinal: true)
  public var Companion: MultipartBody.Companion!

  @JavaStaticField(isFinal: true)
  public var MIXED: MediaType!

  @JavaStaticField(isFinal: true)
  public var ALTERNATIVE: MediaType!

  @JavaStaticField(isFinal: true)
  public var DIGEST: MediaType!

  @JavaStaticField(isFinal: true)
  public var PARALLEL: MediaType!

  @JavaStaticField(isFinal: true)
  public var FORM: MediaType!
}
