// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension MultipartReader {
  @JavaClass("okhttp3.MultipartReader$Part", implements: Closeable.self)
  open class Part: JavaObject {
    /// Java method `headers`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers okhttp3.MultipartReader$Part.headers()
    /// ```
  @JavaMethod
  open func headers() -> Headers!

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.MultipartReader$Part.close()
    /// ```
  @JavaMethod
  open func close()
  }
}
