// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension MultipartBody {
  @JavaClass("okhttp3.MultipartBody$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

    /// Java method `setType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartBody$Builder okhttp3.MultipartBody$Builder.setType(okhttp3.MediaType)
    /// ```
  @JavaMethod
  open func setType(_ arg0: MediaType?) -> MultipartBody.Builder!

    /// Java method `addPart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartBody$Builder okhttp3.MultipartBody$Builder.addPart(okhttp3.Headers,okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func addPart(_ arg0: Headers?, _ arg1: RequestBody?) -> MultipartBody.Builder!

    /// Java method `addPart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartBody$Builder okhttp3.MultipartBody$Builder.addPart(okhttp3.MultipartBody$Part)
    /// ```
  @JavaMethod
  open func addPart(_ arg0: MultipartBody.Part?) -> MultipartBody.Builder!

    /// Java method `addPart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartBody$Builder okhttp3.MultipartBody$Builder.addPart(okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func addPart(_ arg0: RequestBody?) -> MultipartBody.Builder!

    /// Java method `addFormDataPart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartBody$Builder okhttp3.MultipartBody$Builder.addFormDataPart(java.lang.String,java.lang.String,okhttp3.RequestBody)
    /// ```
  @JavaMethod
  open func addFormDataPart(_ arg0: String, _ arg1: String, _ arg2: RequestBody?) -> MultipartBody.Builder!

    /// Java method `addFormDataPart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartBody$Builder okhttp3.MultipartBody$Builder.addFormDataPart(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addFormDataPart(_ arg0: String, _ arg1: String) -> MultipartBody.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartBody okhttp3.MultipartBody$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> MultipartBody!
  }
}
