// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension MultipartReader {
  @JavaClass("okhttp3.MultipartReader$Companion")
  open class Companion: JavaObject {

  }
}
