// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.MultipartReader", implements: Closeable.self)
open class MultipartReader: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ResponseBody?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: BufferedSource?, _ arg1: String, environment: JNIEnvironment? = nil) throws

    /// Java method `boundary`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.MultipartReader.boundary()
    /// ```
  @JavaMethod
  open func boundary() -> String

    /// Java method `nextPart`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.MultipartReader$Part okhttp3.MultipartReader.nextPart() throws java.io.IOException
    /// ```
  @JavaMethod
  open func nextPart() throws -> MultipartReader.Part!

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void okhttp3.MultipartReader.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open func close() throws
}
extension JavaClass<MultipartReader> {
  @JavaStaticField(isFinal: true)
  public var Companion: MultipartReader.Companion!

    /// Java method `access$getSource$p`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final okio.BufferedSource okhttp3.MultipartReader.access$getSource$p(okhttp3.MultipartReader)
    /// ```
  @JavaStaticMethod
  public func access$getSource$p(_ arg0: MultipartReader?) -> BufferedSource!

    /// Java method `access$currentPartBytesRemaining`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static final long okhttp3.MultipartReader.access$currentPartBytesRemaining(okhttp3.MultipartReader,long)
    /// ```
  @JavaStaticMethod
  public func access$currentPartBytesRemaining(_ arg0: MultipartReader?, _ arg1: Int64) -> Int64
}
