// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension MultipartBody {
  @JavaClass("okhttp3.MultipartBody$Companion")
  open class Companion: JavaObject {

  }
}
