// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.OkHttpClient", implements: Call.Factory.self, WebSocket.Factory.self)
open class OkHttpClient: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: OkHttpClient.Builder?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `-deprecated_proxyAuthenticator`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Authenticator okhttp3.OkHttpClient.-deprecated_proxyAuthenticator()
    /// ```
  @JavaMethod
  open func `-deprecated_proxyAuthenticator`() -> Authenticator!

    /// Java method `-deprecated_connectionSpecs`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.ConnectionSpec> okhttp3.OkHttpClient.-deprecated_connectionSpecs()
    /// ```
  @JavaMethod
  open func `-deprecated_connectionSpecs`() -> List<ConnectionSpec>!

    /// Java method `-deprecated_certificatePinner`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CertificatePinner okhttp3.OkHttpClient.-deprecated_certificatePinner()
    /// ```
  @JavaMethod
  open func `-deprecated_certificatePinner`() -> CertificatePinner!

    /// Java method `networkInterceptors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient.networkInterceptors()
    /// ```
  @JavaMethod
  open func networkInterceptors() -> List<Interceptor>!

    /// Java method `eventListenerFactory`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.EventListener$Factory okhttp3.OkHttpClient.eventListenerFactory()
    /// ```
  @JavaMethod
  open func eventListenerFactory() -> EventListener.Factory!

    /// Java method `retryOnConnectionFailure`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient.retryOnConnectionFailure()
    /// ```
  @JavaMethod
  open func retryOnConnectionFailure() -> Bool

    /// Java method `minWebSocketMessageToCompress`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final long okhttp3.OkHttpClient.minWebSocketMessageToCompress()
    /// ```
  @JavaMethod
  open func minWebSocketMessageToCompress() -> Int64

    /// Java method `connectTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.connectTimeoutMillis()
    /// ```
  @JavaMethod
  open func connectTimeoutMillis() -> Int32

    /// Java method `-deprecated_dispatcher`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Dispatcher okhttp3.OkHttpClient.-deprecated_dispatcher()
    /// ```
  @JavaMethod
  open func `-deprecated_dispatcher`() -> Dispatcher!

    /// Java method `-deprecated_connectionPool`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionPool okhttp3.OkHttpClient.-deprecated_connectionPool()
    /// ```
  @JavaMethod
  open func `-deprecated_connectionPool`() -> ConnectionPool!

    /// Java method `-deprecated_interceptors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient.-deprecated_interceptors()
    /// ```
  @JavaMethod
  open func `-deprecated_interceptors`() -> List<Interceptor>!

    /// Java method `-deprecated_networkInterceptors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient.-deprecated_networkInterceptors()
    /// ```
  @JavaMethod
  open func `-deprecated_networkInterceptors`() -> List<Interceptor>!

    /// Java method `-deprecated_eventListenerFactory`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.EventListener$Factory okhttp3.OkHttpClient.-deprecated_eventListenerFactory()
    /// ```
  @JavaMethod
  open func `-deprecated_eventListenerFactory`() -> EventListener.Factory!

    /// Java method `-deprecated_authenticator`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Authenticator okhttp3.OkHttpClient.-deprecated_authenticator()
    /// ```
  @JavaMethod
  open func `-deprecated_authenticator`() -> Authenticator!

    /// Java method `-deprecated_followRedirects`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient.-deprecated_followRedirects()
    /// ```
  @JavaMethod
  open func `-deprecated_followRedirects`() -> Bool

    /// Java method `-deprecated_followSslRedirects`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient.-deprecated_followSslRedirects()
    /// ```
  @JavaMethod
  open func `-deprecated_followSslRedirects`() -> Bool

    /// Java method `-deprecated_cookieJar`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CookieJar okhttp3.OkHttpClient.-deprecated_cookieJar()
    /// ```
  @JavaMethod
  open func `-deprecated_cookieJar`() -> CookieJar!

    /// Java method `-deprecated_callTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.-deprecated_callTimeoutMillis()
    /// ```
  @JavaMethod
  open func `-deprecated_callTimeoutMillis`() -> Int32

    /// Java method `-deprecated_connectTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.-deprecated_connectTimeoutMillis()
    /// ```
  @JavaMethod
  open func `-deprecated_connectTimeoutMillis`() -> Int32

    /// Java method `-deprecated_readTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.-deprecated_readTimeoutMillis()
    /// ```
  @JavaMethod
  open func `-deprecated_readTimeoutMillis`() -> Int32

    /// Java method `-deprecated_writeTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.-deprecated_writeTimeoutMillis()
    /// ```
  @JavaMethod
  open func `-deprecated_writeTimeoutMillis`() -> Int32

    /// Java method `-deprecated_pingIntervalMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.-deprecated_pingIntervalMillis()
    /// ```
  @JavaMethod
  open func `-deprecated_pingIntervalMillis`() -> Int32

    /// Java method `newCall`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Call okhttp3.OkHttpClient.newCall(okhttp3.Request)
    /// ```
  @JavaMethod
  open func newCall(_ arg0: Request?) -> Call!

    /// Java method `dns`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Dns okhttp3.OkHttpClient.dns()
    /// ```
  @JavaMethod
  open func dns() -> Dns!

    /// Java method `proxyAuthenticator`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Authenticator okhttp3.OkHttpClient.proxyAuthenticator()
    /// ```
  @JavaMethod
  open func proxyAuthenticator() -> Authenticator!

    /// Java method `connectionSpecs`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.ConnectionSpec> okhttp3.OkHttpClient.connectionSpecs()
    /// ```
  @JavaMethod
  open func connectionSpecs() -> List<ConnectionSpec>!

    /// Java method `certificatePinner`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CertificatePinner okhttp3.OkHttpClient.certificatePinner()
    /// ```
  @JavaMethod
  open func certificatePinner() -> CertificatePinner!

    /// Java method `-deprecated_dns`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Dns okhttp3.OkHttpClient.-deprecated_dns()
    /// ```
  @JavaMethod
  open func `-deprecated_dns`() -> Dns!

    /// Java method `dispatcher`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Dispatcher okhttp3.OkHttpClient.dispatcher()
    /// ```
  @JavaMethod
  open func dispatcher() -> Dispatcher!

    /// Java method `connectionPool`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ConnectionPool okhttp3.OkHttpClient.connectionPool()
    /// ```
  @JavaMethod
  open func connectionPool() -> ConnectionPool!

    /// Java method `interceptors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.util.List<okhttp3.Interceptor> okhttp3.OkHttpClient.interceptors()
    /// ```
  @JavaMethod
  open func interceptors() -> List<Interceptor>!

    /// Java method `authenticator`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Authenticator okhttp3.OkHttpClient.authenticator()
    /// ```
  @JavaMethod
  open func authenticator() -> Authenticator!

    /// Java method `followRedirects`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient.followRedirects()
    /// ```
  @JavaMethod
  open func followRedirects() -> Bool

    /// Java method `followSslRedirects`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient.followSslRedirects()
    /// ```
  @JavaMethod
  open func followSslRedirects() -> Bool

    /// Java method `cookieJar`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.CookieJar okhttp3.OkHttpClient.cookieJar()
    /// ```
  @JavaMethod
  open func cookieJar() -> CookieJar!

    /// Java method `callTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.callTimeoutMillis()
    /// ```
  @JavaMethod
  open func callTimeoutMillis() -> Int32

    /// Java method `readTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.readTimeoutMillis()
    /// ```
  @JavaMethod
  open func readTimeoutMillis() -> Int32

    /// Java method `writeTimeoutMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.writeTimeoutMillis()
    /// ```
  @JavaMethod
  open func writeTimeoutMillis() -> Int32

    /// Java method `pingIntervalMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.OkHttpClient.pingIntervalMillis()
    /// ```
  @JavaMethod
  open func pingIntervalMillis() -> Int32

    /// Java method `newBuilder`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient.newBuilder()
    /// ```
  @JavaMethod
  open func newBuilder() -> OkHttpClient.Builder!

    /// Java method `newWebSocket`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.WebSocket okhttp3.OkHttpClient.newWebSocket(okhttp3.Request,okhttp3.WebSocketListener)
    /// ```
  @JavaMethod
  open func newWebSocket(_ arg0: Request?, _ arg1: WebSocketListener?) -> WebSocket!

    /// Java method `-deprecated_cache`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cache okhttp3.OkHttpClient.-deprecated_cache()
    /// ```
  @JavaMethod
  open func `-deprecated_cache`() -> Cache!

    /// Java method `-deprecated_retryOnConnectionFailure`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean okhttp3.OkHttpClient.-deprecated_retryOnConnectionFailure()
    /// ```
  @JavaMethod
  open func `-deprecated_retryOnConnectionFailure`() -> Bool

    /// Java method `cache`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Cache okhttp3.OkHttpClient.cache()
    /// ```
  @JavaMethod
  open func cache() -> Cache!

    /// Java method `clone`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Object okhttp3.OkHttpClient.clone()
    /// ```
  @JavaMethod
  open override func clone() -> JavaObject!
}
extension JavaClass<OkHttpClient> {
  @JavaStaticField(isFinal: true)
  public var Companion: OkHttpClient.Companion!
}
