// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("okhttp3.OkHttp")
open class OkHttp: JavaObject {

}
extension JavaClass<OkHttp> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: OkHttp!

  @JavaStaticField(isFinal: true)
  public var VERSION: String
}
