// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("okhttp3.Request")
open class Request: JavaObject {
  /// Java method `-deprecated_headers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Headers okhttp3.Request.-deprecated_headers()
  /// ```
@JavaMethod
  open func `-deprecated_headers`() -> Headers!

  /// Java method `-deprecated_cacheControl`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.CacheControl okhttp3.Request.-deprecated_cacheControl()
  /// ```
@JavaMethod
  open func `-deprecated_cacheControl`() -> CacheControl!

  /// Java method `isHttps`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Request.isHttps()
  /// ```
@JavaMethod
  open func isHttps() -> Bool

  /// Java method `headers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.List<java.lang.String> okhttp3.Request.headers(java.lang.String)
  /// ```
@JavaMethod
  open func headers(_ arg0: String) -> List<JavaString>!

  /// Java method `headers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Headers okhttp3.Request.headers()
  /// ```
@JavaMethod
  open func headers() -> Headers!

  /// Java method `-deprecated_url`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.HttpUrl okhttp3.Request.-deprecated_url()
  /// ```
@JavaMethod
  open func `-deprecated_url`() -> HttpUrl!

  /// Java method `-deprecated_body`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.RequestBody okhttp3.Request.-deprecated_body()
  /// ```
@JavaMethod
  open func `-deprecated_body`() -> RequestBody!

  /// Java method `newBuilder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Request$Builder okhttp3.Request.newBuilder()
  /// ```
@JavaMethod
  open func newBuilder() -> Request.Builder!

  /// Java method `cacheControl`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.CacheControl okhttp3.Request.cacheControl()
  /// ```
@JavaMethod
  open func cacheControl() -> CacheControl!

  /// Java method `-deprecated_method`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Request.-deprecated_method()
  /// ```
@JavaMethod
  open func `-deprecated_method`() -> String

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String okhttp3.Request.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `method`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Request.method()
  /// ```
@JavaMethod
  open func method() -> String

  /// Java method `url`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.HttpUrl okhttp3.Request.url()
  /// ```
@JavaMethod
  open func url() -> HttpUrl!

  /// Java method `body`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.RequestBody okhttp3.Request.body()
  /// ```
@JavaMethod
  open func body() -> RequestBody!

  /// Java method `tag`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.Object okhttp3.Request.tag()
  /// ```
@JavaMethod
  open func tag() -> JavaObject!

  /// Java method `tag`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final <T> T okhttp3.Request.tag(java.lang.Class<? extends T>)
  /// ```
@JavaMethod(typeErasedResult: "T!")
  open func tag<T: AnyJavaObject>(_ arg0: JavaClass<T>?) -> T!

  /// Java method `header`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String okhttp3.Request.header(java.lang.String)
  /// ```
@JavaMethod
  open func header(_ arg0: String) -> String
}
