// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension Response {
  @JavaClass("okhttp3.Response$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Response?, environment: JNIEnvironment? = nil)

    /// Java method `headers`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.headers(okhttp3.Headers)
    /// ```
  @JavaMethod
  open func headers(_ arg0: Headers?) -> Response.Builder!

    /// Java method `handshake`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.handshake(okhttp3.Handshake)
    /// ```
  @JavaMethod
  open func handshake(_ arg0: Handshake?) -> Response.Builder!

    /// Java method `networkResponse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.networkResponse(okhttp3.Response)
    /// ```
  @JavaMethod
  open func networkResponse(_ arg0: Response?) -> Response.Builder!

    /// Java method `getHeaders$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Headers$Builder okhttp3.Response$Builder.getHeaders$okhttp()
    /// ```
  @JavaMethod
  open func getHeaders$okhttp() -> Headers.Builder!

    /// Java method `setHeaders$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setHeaders$okhttp(okhttp3.Headers$Builder)
    /// ```
  @JavaMethod
  open func setHeaders$okhttp(_ arg0: Headers.Builder?)

    /// Java method `getBody$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.ResponseBody okhttp3.Response$Builder.getBody$okhttp()
    /// ```
  @JavaMethod
  open func getBody$okhttp() -> ResponseBody!

    /// Java method `setBody$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setBody$okhttp(okhttp3.ResponseBody)
    /// ```
  @JavaMethod
  open func setBody$okhttp(_ arg0: ResponseBody?)

    /// Java method `addHeader`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.addHeader(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func addHeader(_ arg0: String, _ arg1: String) -> Response.Builder!

    /// Java method `removeHeader`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.removeHeader(java.lang.String)
    /// ```
  @JavaMethod
  open func removeHeader(_ arg0: String) -> Response.Builder!

    /// Java method `cacheResponse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.cacheResponse(okhttp3.Response)
    /// ```
  @JavaMethod
  open func cacheResponse(_ arg0: Response?) -> Response.Builder!

    /// Java method `priorResponse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.priorResponse(okhttp3.Response)
    /// ```
  @JavaMethod
  open func priorResponse(_ arg0: Response?) -> Response.Builder!

    /// Java method `getRequest$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Request okhttp3.Response$Builder.getRequest$okhttp()
    /// ```
  @JavaMethod
  open func getRequest$okhttp() -> Request!

    /// Java method `setRequest$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setRequest$okhttp(okhttp3.Request)
    /// ```
  @JavaMethod
  open func setRequest$okhttp(_ arg0: Request?)

    /// Java method `getCode$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int okhttp3.Response$Builder.getCode$okhttp()
    /// ```
  @JavaMethod
  open func getCode$okhttp() -> Int32

    /// Java method `setCode$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setCode$okhttp(int)
    /// ```
  @JavaMethod
  open func setCode$okhttp(_ arg0: Int32)

    /// Java method `getMessage$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String okhttp3.Response$Builder.getMessage$okhttp()
    /// ```
  @JavaMethod
  open func getMessage$okhttp() -> String

    /// Java method `setMessage$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setMessage$okhttp(java.lang.String)
    /// ```
  @JavaMethod
  open func setMessage$okhttp(_ arg0: String)

    /// Java method `sentRequestAtMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.sentRequestAtMillis(long)
    /// ```
  @JavaMethod
  open func sentRequestAtMillis(_ arg0: Int64) -> Response.Builder!

    /// Java method `receivedResponseAtMillis`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.receivedResponseAtMillis(long)
    /// ```
  @JavaMethod
  open func receivedResponseAtMillis(_ arg0: Int64) -> Response.Builder!

    /// Java method `getHandshake$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Handshake okhttp3.Response$Builder.getHandshake$okhttp()
    /// ```
  @JavaMethod
  open func getHandshake$okhttp() -> Handshake!

    /// Java method `setHandshake$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setHandshake$okhttp(okhttp3.Handshake)
    /// ```
  @JavaMethod
  open func setHandshake$okhttp(_ arg0: Handshake?)

    /// Java method `getNetworkResponse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Response okhttp3.Response$Builder.getNetworkResponse$okhttp()
    /// ```
  @JavaMethod
  open func getNetworkResponse$okhttp() -> Response!

    /// Java method `setNetworkResponse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setNetworkResponse$okhttp(okhttp3.Response)
    /// ```
  @JavaMethod
  open func setNetworkResponse$okhttp(_ arg0: Response?)

    /// Java method `getCacheResponse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Response okhttp3.Response$Builder.getCacheResponse$okhttp()
    /// ```
  @JavaMethod
  open func getCacheResponse$okhttp() -> Response!

    /// Java method `setCacheResponse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setCacheResponse$okhttp(okhttp3.Response)
    /// ```
  @JavaMethod
  open func setCacheResponse$okhttp(_ arg0: Response?)

    /// Java method `getPriorResponse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final okhttp3.Response okhttp3.Response$Builder.getPriorResponse$okhttp()
    /// ```
  @JavaMethod
  open func getPriorResponse$okhttp() -> Response!

    /// Java method `setPriorResponse$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setPriorResponse$okhttp(okhttp3.Response)
    /// ```
  @JavaMethod
  open func setPriorResponse$okhttp(_ arg0: Response?)

    /// Java method `getSentRequestAtMillis$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final long okhttp3.Response$Builder.getSentRequestAtMillis$okhttp()
    /// ```
  @JavaMethod
  open func getSentRequestAtMillis$okhttp() -> Int64

    /// Java method `setSentRequestAtMillis$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setSentRequestAtMillis$okhttp(long)
    /// ```
  @JavaMethod
  open func setSentRequestAtMillis$okhttp(_ arg0: Int64)

    /// Java method `getReceivedResponseAtMillis$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final long okhttp3.Response$Builder.getReceivedResponseAtMillis$okhttp()
    /// ```
  @JavaMethod
  open func getReceivedResponseAtMillis$okhttp() -> Int64

    /// Java method `setReceivedResponseAtMillis$okhttp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void okhttp3.Response$Builder.setReceivedResponseAtMillis$okhttp(long)
    /// ```
  @JavaMethod
  open func setReceivedResponseAtMillis$okhttp(_ arg0: Int64)

    /// Java method `code`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.code(int)
    /// ```
  @JavaMethod
  open func code(_ arg0: Int32) -> Response.Builder!

    /// Java method `message`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.message(java.lang.String)
    /// ```
  @JavaMethod
  open func message(_ arg0: String) -> Response.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response okhttp3.Response$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> Response!

    /// Java method `body`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.body(okhttp3.ResponseBody)
    /// ```
  @JavaMethod
  open func body(_ arg0: ResponseBody?) -> Response.Builder!

    /// Java method `request`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.request(okhttp3.Request)
    /// ```
  @JavaMethod
  open func request(_ arg0: Request?) -> Response.Builder!

    /// Java method `header`.
    ///
    /// ### Java method signature
    /// ```java
    /// public okhttp3.Response$Builder okhttp3.Response$Builder.header(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func header(_ arg0: String, _ arg1: String) -> Response.Builder!
  }
}
