// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("okhttp3.Route")
open class Route: JavaObject {
  /// Java method `-deprecated_address`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Address okhttp3.Route.-deprecated_address()
  /// ```
@JavaMethod
  open func `-deprecated_address`() -> Address!

  /// Java method `requiresTunnel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean okhttp3.Route.requiresTunnel()
  /// ```
@JavaMethod
  open func requiresTunnel() -> Bool

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean okhttp3.Route.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String okhttp3.Route.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int okhttp3.Route.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `address`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final okhttp3.Address okhttp3.Route.address()
  /// ```
@JavaMethod
  open func address() -> Address!
}
